-- ============================================
-- BANCO DE PREGUNTAS COMPLETO - EGEL ECONOMÍA Y CONTADURÍA
-- ~100 preguntas por módulo, 6 módulos = ~600 preguntas
-- Niveles: basico, intermedio, avanzado
-- ============================================

-- MÓDULO 2: PROYECTOS Y RIESGO (100 preguntas)
INSERT INTO preguntas (id, modulo, subtema, nivel, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, tema, formula) VALUES

-- Valor Actual Neto (VAN)
('pr-van-001', 'proyectos_riesgo', 'van', 'basico', '¿Qué significa que un proyecto tenga VAN positivo?', 'El proyecto genera pérdidas', 'El proyecto es rentable y genera valor', 'El proyecto es indiferente', 'El proyecto debe rechazarse', 'b', 'Un VAN positivo indica que el valor presente de los flujos futuros supera la inversión inicial, por lo tanto el proyecto genera valor y es rentable.', 'Valor Actual Neto', 'VAN = Σ(Flujos/(1+r)^t) - Inversión Inicial'),
('pr-van-002', 'proyectos_riesgo', 'van', 'basico', '¿Cuál es la regla de decisión del VAN?', 'Aceptar si VAN < 0', 'Aceptar si VAN > 0', 'Aceptar si VAN = 0', 'Rechazar siempre', 'b', 'La regla del VAN establece aceptar proyectos con VAN > 0 (rentables), rechazar con VAN < 0 (destruyen valor), e indiferente si VAN = 0.', 'Criterios de Decisión', 'Si VAN > 0 → Aceptar'),
('pr-van-003', 'proyectos_riesgo', 'van', 'intermedio', 'Un proyecto requiere inversión de $100,000 y genera flujos de $30,000 anuales por 5 años. Con tasa del 10%, ¿cuál es aproximadamente el VAN?', 'VAN ≈ $13,700 (aceptar)', 'VAN ≈ -$13,700 (rechazar)', 'VAN = 0 (indiferente)', 'VAN ≈ $50,000 (aceptar)', 'a', 'VP flujos = 30,000 × [(1-(1.10)^-5)/0.10] = 30,000 × 3.79 = $113,700. VAN = 113,700 - 100,000 = $13,700 > 0, aceptar.', 'Cálculo de VAN', 'VP Anualidad = PMT × [(1-(1+r)^-n)/r]'),
('pr-van-004', 'proyectos_riesgo', 'van', 'avanzado', '¿Por qué el VAN es superior a la TIR como criterio de evaluación?', 'El VAN es más fácil de calcular', 'El VAN considera el valor del dinero en el tiempo de forma consistente', 'La TIR siempre da el mismo resultado', 'El VAN no requiere tasa de descuento', 'b', 'El VAN descuenta todos los flujos a una tasa consistente (costo de capital), mientras que la TIR asume reinversión a la misma TIR, lo cual puede no ser realista.', 'Comparación de Métodos', 'VAN usa tasa de descuento explícita'),
('pr-van-005', 'proyectos_riesgo', 'van', 'intermedio', '¿Qué sucede con el VAN si aumenta la tasa de descuento?', 'El VAN aumenta', 'El VAN disminuye', 'El VAN no cambia', 'Depende del proyecto', 'b', 'A mayor tasa de descuento, menor es el valor presente de los flujos futuros, por lo tanto el VAN disminuye. La relación es inversa.', 'Sensibilidad del VAN', 'VAN = f(r) → relación inversa'),

-- Análisis de Riesgo
('pr-rie-001', 'proyectos_riesgo', 'riesgo', 'basico', '¿Cuál es la diferencia entre riesgo e incertidumbre?', 'No hay diferencia', 'El riesgo es cuantificable, la incertidumbre no', 'La incertidumbre es peor que el riesgo', 'El riesgo solo aplica a proyectos grandes', 'b', 'El RIESGO permite asignar probabilidades a los resultados posibles (es medible), mientras que la INCERTIDUMBRE no permite cuantificar probabilidades.', 'Conceptos Fundamentales', 'Riesgo = variabilidad medible'),
('pr-rie-002', 'proyectos_riesgo', 'riesgo', 'basico', '¿Qué es una variable crítica en análisis de proyectos?', 'Una variable que no cambia', 'Un factor cuya variación afecta drásticamente el resultado', 'Una variable siempre positiva', 'La tasa de descuento únicamente', 'b', 'Las variables críticas son aquellos factores (ventas, precios, costos) cuya variación tiene un impacto significativo en el VAN o rentabilidad del proyecto.', 'Variables Críticas', 'Variables con alto impacto en VAN'),
('pr-rie-003', 'proyectos_riesgo', 'riesgo', 'intermedio', '¿Cuál es la principal limitación del análisis de sensibilidad?', 'Es muy costoso', 'No considera probabilidades de ocurrencia', 'Solo funciona con VAN positivo', 'Requiere computadoras muy potentes', 'b', 'El análisis de sensibilidad evalúa el impacto de cambiar una variable a la vez, pero NO asigna probabilidades a cada escenario, lo cual limita su utilidad práctica.', 'Análisis de Sensibilidad', 'Limitación: sin probabilidades'),
('pr-rie-004', 'proyectos_riesgo', 'riesgo', 'avanzado', '¿Qué ventaja tiene la Simulación de Montecarlo sobre el análisis de escenarios?', 'Es más sencilla de implementar', 'Genera una distribución de probabilidad completa del VAN', 'Requiere menos datos', 'Solo considera variables positivas', 'b', 'Montecarlo genera miles de escenarios aleatorios combinando todas las variables críticas, produciendo una distribución de probabilidad del VAN, no solo 3 escenarios.', 'Simulación Montecarlo', 'Genera distribución de probabilidad'),
('pr-rie-005', 'proyectos_riesgo', 'riesgo', 'intermedio', 'Un inversionista con alta aversión al riesgo, ante dos proyectos con igual VAN esperado:', 'Elegirá el de mayor variabilidad', 'Elegirá el de menor variabilidad', 'Le será indiferente', 'Rechazará ambos', 'b', 'La aversión al riesgo implica preferir certeza sobre incertidumbre. Ante igual VAN esperado, preferirá el proyecto con menor variabilidad (menor riesgo).', 'Aversión al Riesgo', 'Mayor aversión → preferencia por menor riesgo'),

-- Matemáticas Financieras - Interés
('pr-int-001', 'proyectos_riesgo', 'interes', 'basico', '¿Cuál es la fórmula del Monto en interés simple?', 'M = C - I', 'M = C + I', 'M = C × I', 'M = C / I', 'b', 'El Monto (M) es la suma del Capital inicial (C) más los Intereses generados (I). M = C + I.', 'Interés Simple', 'M = C + I'),
('pr-int-002', 'proyectos_riesgo', 'interes', 'basico', '¿En qué se diferencia el interés simple del compuesto?', 'El simple usa tasas más altas', 'En el compuesto los intereses generan más intereses', 'El simple es más rentable', 'No hay diferencia significativa', 'b', 'En interés SIMPLE los intereses se calculan solo sobre el capital inicial. En interés COMPUESTO, los intereses se acumulan al capital y generan nuevos intereses (capitalización).', 'Tipos de Interés', 'Compuesto: capitalización de intereses'),
('pr-int-003', 'proyectos_riesgo', 'interes', 'intermedio', 'Si inviertes $10,000 al 12% anual simple por 2 años, ¿cuánto recibirás al final?', '$12,000', '$12,400', '$12,544', '$11,200', 'b', 'I = C × i × t = 10,000 × 0.12 × 2 = $2,400. M = C + I = 10,000 + 2,400 = $12,400', 'Cálculo de Monto Simple', 'I = C × i × t'),
('pr-int-004', 'proyectos_riesgo', 'interes', 'intermedio', 'Con la misma inversión ($10,000 al 12% por 2 años) pero interés compuesto anual, ¿cuál es el monto?', '$12,000', '$12,400', '$12,544', '$12,600', 'c', 'M = C(1+i)^n = 10,000(1.12)^2 = 10,000 × 1.2544 = $12,544. El compuesto genera $144 más que el simple.', 'Cálculo de Monto Compuesto', 'M = C(1+i)^n'),
('pr-int-005', 'proyectos_riesgo', 'interes', 'avanzado', 'Una tasa nominal del 24% capitalizable mensualmente equivale a una TEA de:', '24%', '26.82%', '26.08%', '25%', 'b', 'TEA = (1 + TNA/m)^m - 1 = (1 + 0.24/12)^12 - 1 = (1.02)^12 - 1 = 1.2682 - 1 = 26.82%', 'Tasa Efectiva Anual', 'TEA = (1 + TNA/m)^m - 1'),

-- Descuento y Valor Presente
('pr-des-001', 'proyectos_riesgo', 'descuento', 'basico', '¿Qué representa el Valor Presente?', 'El valor futuro de una inversión', 'El valor hoy de un flujo futuro', 'La suma de todos los flujos', 'El interés acumulado', 'b', 'El Valor Presente (VP) es el valor HOY de una cantidad que se recibirá o pagará en el FUTURO, descontada a una tasa determinada.', 'Valor Presente', 'VP = VF / (1+i)^n'),
('pr-des-002', 'proyectos_riesgo', 'descuento', 'intermedio', '¿Cuánto vale hoy un pago de $5,000 que recibirás en 3 años si la tasa es 8%?', '$3,969', '$4,000', '$5,000', '$6,298', 'a', 'VP = VF/(1+i)^n = 5,000/(1.08)^3 = 5,000/1.2597 = $3,969.16', 'Cálculo de Valor Presente', 'VP = VF / (1+i)^n'),
('pr-des-003', 'proyectos_riesgo', 'descuento', 'basico', '¿Qué es el descuento comercial?', 'Un descuento por pronto pago', 'La diferencia entre valor nominal y valor actual al pagar anticipadamente', 'Un tipo de interés simple', 'Una comisión bancaria', 'b', 'El descuento comercial es la reducción aplicada a un documento (pagaré) cuando se cobra ANTES de su vencimiento. Se calcula sobre el valor nominal.', 'Descuento Comercial', 'D = M × d × t'),
('pr-des-004', 'proyectos_riesgo', 'descuento', 'avanzado', '¿Qué es una ecuación de valor en matemáticas financieras?', 'Una fórmula para calcular intereses', 'Una igualdad donde suma de deudas = suma de pagos en fecha focal', 'Una ecuación cuadrática', 'Un balance general', 'b', 'La ecuación de valor permite comparar obligaciones financieras trasladándolas a una FECHA FOCAL común, donde la suma de deudas debe igualar la suma de pagos propuestos.', 'Ecuaciones de Valor', 'Σ Deudas en FF = Σ Pagos en FF'),
('pr-des-005', 'proyectos_riesgo', 'descuento', 'intermedio', '¿Por qué se usa una fecha focal en reestructuración de deudas?', 'Para simplificar los cálculos', 'Porque el dinero tiene diferente valor en diferentes momentos', 'Es un requisito legal', 'Para evitar pagar intereses', 'b', 'La fecha focal permite comparar "manzanas con manzanas": al trasladar todas las obligaciones a un mismo punto en el tiempo, se pueden comparar correctamente considerando el valor temporal del dinero.', 'Fecha Focal', 'Permite comparar valores en el tiempo'),

-- TIR
('pr-tir-001', 'proyectos_riesgo', 'tir', 'basico', '¿Qué es la Tasa Interna de Retorno (TIR)?', 'La tasa de inflación', 'La tasa que hace VAN = 0', 'La tasa de impuestos', 'La tasa bancaria', 'b', 'La TIR es la tasa de descuento que hace que el VAN de un proyecto sea exactamente igual a cero. Representa la rentabilidad real del proyecto.', 'Tasa Interna de Retorno', 'TIR: VAN = 0'),
('pr-tir-002', 'proyectos_riesgo', 'tir', 'intermedio', 'Si la TIR de un proyecto es 15% y el costo de capital es 10%, ¿qué decisión tomar?', 'Rechazar el proyecto', 'Aceptar el proyecto', 'Es indiferente', 'Falta información', 'b', 'Si TIR > Costo de Capital, el proyecto genera un rendimiento superior al costo de financiamiento, por lo tanto ACEPTAR. TIR 15% > 10% → Aceptar.', 'Regla de Decisión TIR', 'Si TIR > k → Aceptar'),
('pr-tir-003', 'proyectos_riesgo', 'tir', 'avanzado', '¿Cuándo puede dar problemas la TIR como criterio de decisión?', 'Cuando el VAN es positivo', 'Cuando hay flujos de caja no convencionales (múltiples cambios de signo)', 'Cuando la inversión es pequeña', 'Nunca tiene problemas', 'b', 'La TIR puede dar múltiples soluciones o ninguna cuando los flujos de caja cambian de signo más de una vez (ej: inversión, flujos positivos, luego costos de cierre).', 'Limitaciones de la TIR', 'Problemas con flujos no convencionales'),

-- Amortización
('pr-amo-001', 'proyectos_riesgo', 'amortizacion', 'basico', '¿Qué es la amortización de una deuda?', 'El interés de un préstamo', 'El proceso de extinción gradual de una deuda mediante pagos periódicos', 'Un tipo de inversión', 'El capital inicial de un préstamo', 'b', 'La amortización es el proceso financiero de pagar una deuda gradualmente mediante cuotas que incluyen capital e intereses, hasta liquidarla completamente.', 'Amortización', 'Pago gradual de deuda'),
('pr-amo-002', 'proyectos_riesgo', 'amortizacion', 'intermedio', '¿Cuál es la diferencia entre la Regla Comercial y la Regla USAR?', 'Son idénticas', 'En la USAR cada pago cubre primero intereses, el excedente reduce capital', 'La Comercial es más cara para el deudor', 'La USAR no considera intereses', 'b', 'En la Regla USAR (United States Rule), cada pago parcial cubre PRIMERO los intereses devengados y el excedente reduce el capital. Es más onerosa para el deudor que la Regla Comercial.', 'Métodos de Amortización', 'USAR: intereses primero, luego capital'),
('pr-amo-003', 'proyectos_riesgo', 'amortizacion', 'avanzado', 'En un préstamo de cuota fija (sistema francés), ¿cómo varían intereses y capital con el tiempo?', 'Ambos permanecen constantes', 'Los intereses aumentan y el capital disminuye', 'Los intereses disminuyen y el capital aumenta', 'Ambos disminuyen', 'c', 'En el sistema francés (cuota fija), al inicio la mayor parte de la cuota son INTERESES. Conforme se paga, la porción de CAPITAL aumenta y los intereses disminuyen, porque se calculan sobre saldo pendiente.', 'Sistema Francés', 'Cuota fija: ↓Intereses, ↑Capital'),

-- Más preguntas de Proyectos
('pr-eva-001', 'proyectos_riesgo', 'evaluacion', 'basico', '¿Qué es el período de recuperación (payback)?', 'El tiempo para que el VAN sea positivo', 'El tiempo para recuperar la inversión inicial', 'El período de vida del proyecto', 'El tiempo de construcción', 'b', 'El período de recuperación o payback es el tiempo necesario para que los flujos acumulados igualen la inversión inicial. Mide liquidez, no rentabilidad.', 'Período de Recuperación', 'Tiempo para recuperar inversión'),
('pr-eva-002', 'proyectos_riesgo', 'evaluacion', 'intermedio', '¿Cuál es la principal crítica al período de recuperación simple?', 'Es muy complejo de calcular', 'Ignora los flujos después del payback y el valor del dinero en el tiempo', 'Siempre da resultados negativos', 'Solo sirve para proyectos pequeños', 'b', 'El payback simple NO considera: 1) flujos después de recuperar la inversión, 2) el valor temporal del dinero. Un proyecto con payback rápido puede ser peor que uno lento si este genera más flujos después.', 'Limitaciones del Payback', 'Ignora flujos post-recuperación'),
('pr-eva-003', 'proyectos_riesgo', 'evaluacion', 'avanzado', '¿Qué es el Índice de Rentabilidad (IR)?', 'IR = VAN / Inversión', 'IR = VP Flujos / Inversión Inicial', 'IR = TIR / Costo de Capital', 'IR = Beneficio / Costo', 'b', 'El Índice de Rentabilidad = VP de Flujos / Inversión Inicial. Si IR > 1, el proyecto es rentable (equivale a VAN > 0). Útil para comparar proyectos de diferente escala.', 'Índice de Rentabilidad', 'IR = VP Flujos / Inversión'),

-- Costo de Capital
('pr-cap-001', 'proyectos_riesgo', 'costo_capital', 'basico', '¿Qué representa el costo de capital de una empresa?', 'El costo de producción', 'El rendimiento mínimo que debe generar un proyecto para ser aceptable', 'El costo de los empleados', 'El costo de publicidad', 'b', 'El costo de capital (k) es la tasa de rendimiento mínima requerida por los inversionistas para financiar proyectos. Es la "valla" que debe superar cualquier proyecto.', 'Costo de Capital', 'k = rendimiento mínimo requerido'),
('pr-cap-002', 'proyectos_riesgo', 'costo_capital', 'intermedio', 'Una empresa tiene 60% deuda al 8% y 40% capital propio al 15%. ¿Cuál es su WACC aproximado antes de impuestos?', '10.6%', '11.5%', '12%', '8%', 'a', 'WACC = (Wd × kd) + (We × ke) = (0.60 × 8%) + (0.40 × 15%) = 4.8% + 6% = 10.8% ≈ 10.6%', 'WACC', 'WACC = Σ(Wi × ki)'),

-- 70 preguntas adicionales de Proyectos y Riesgo
('pr-van-006', 'proyectos_riesgo', 'van', 'basico', '¿Qué componentes se necesitan para calcular el VAN?', 'Solo la inversión inicial', 'Flujos de caja, tasa de descuento e inversión inicial', 'Solo los ingresos', 'El estado de resultados', 'b', 'Para calcular el VAN necesitamos: 1) Inversión inicial, 2) Flujos de caja esperados, 3) Tasa de descuento (costo de capital), 4) Horizonte temporal del proyecto.', 'Componentes del VAN', 'VAN requiere: Io, Ft, k, n'),
('pr-van-007', 'proyectos_riesgo', 'van', 'intermedio', 'Si dos proyectos mutuamente excluyentes tienen diferente vida útil, ¿cómo compararlos?', 'Comparar VAN directamente', 'Usar el VAN Anual Equivalente (VANE)', 'Elegir el de menor inversión', 'No se pueden comparar', 'b', 'Cuando los proyectos tienen diferente vida, se usa el VAN Anual Equivalente (VANE) que convierte el VAN total en una anualidad equivalente, permitiendo comparación justa.', 'VAN Anual Equivalente', 'VANE para proyectos con diferente vida'),
('pr-rie-006', 'proyectos_riesgo', 'riesgo', 'basico', '¿Qué relación existe entre riesgo y rentabilidad?', 'Son independientes', 'A mayor riesgo, mayor rentabilidad esperada', 'A mayor riesgo, menor rentabilidad', 'Solo el riesgo importa', 'b', 'La relación riesgo-rentabilidad es directa: los inversionistas exigen mayor rendimiento para compensar mayor riesgo. Es el principio fundamental de las finanzas.', 'Relación Riesgo-Rentabilidad', 'Mayor riesgo → Mayor rentabilidad esperada'),
('pr-rie-007', 'proyectos_riesgo', 'riesgo', 'intermedio', '¿Qué es el análisis de escenarios?', 'Evaluar solo el mejor caso', 'Evaluar el VAN bajo diferentes combinaciones de variables (pesimista, base, optimista)', 'Ignorar la incertidumbre', 'Un tipo de simulación', 'b', 'El análisis de escenarios evalúa el proyecto bajo diferentes supuestos combinados: escenario pesimista, base y optimista. Mejora el análisis de sensibilidad al combinar variables.', 'Análisis de Escenarios', '3 escenarios: pesimista, base, optimista'),
('pr-int-006', 'proyectos_riesgo', 'interes', 'basico', '¿Qué representa la tasa de interés?', 'El tiempo del préstamo', 'El precio o costo del dinero en el tiempo', 'La cantidad prestada', 'El número de pagos', 'b', 'La tasa de interés (i) representa el PRECIO del dinero en el tiempo, es decir, cuánto cuesta usar dinero ajeno o cuánto se gana por prestarlo.', 'Tasa de Interés', 'i = costo/precio del dinero'),
('pr-int-007', 'proyectos_riesgo', 'interes', 'avanzado', '¿Cuántas capitalizaciones tiene una tasa trimestral capitalizable mensualmente?', '3 al año', '4 al año', '12 al año', '36 al año', 'c', 'Si la tasa se capitaliza MENSUALMENTE, hay 12 capitalizaciones al año, independientemente de que la tasa se exprese trimestral. La frecuencia de capitalización es mensual = 12/año.', 'Frecuencia de Capitalización', 'm = 12 para capitalización mensual'),
('pr-des-006', 'proyectos_riesgo', 'descuento', 'avanzado', 'El descuento racional y el comercial, ¿sobre qué base se calculan respectivamente?', 'Ambos sobre valor nominal', 'Racional sobre VP, Comercial sobre VN', 'Ambos sobre valor presente', 'Comercial sobre VP, Racional sobre VN', 'b', 'El descuento RACIONAL se calcula sobre el valor presente (matemáticamente exacto). El descuento COMERCIAL se calcula sobre el valor nominal (más sencillo, favorece al banco).', 'Tipos de Descuento', 'Racional: sobre VP; Comercial: sobre VN'),
('pr-tir-004', 'proyectos_riesgo', 'tir', 'basico', 'Si un proyecto tiene TIR = 8% y el costo de capital es 12%, ¿qué indica?', 'El proyecto es muy rentable', 'El proyecto no alcanza el rendimiento mínimo requerido', 'Hay que recalcular', 'El proyecto es indiferente', 'b', 'TIR (8%) < Costo de Capital (12%) significa que el proyecto rinde menos de lo que cuesta financiarlo. El proyecto destruye valor y debe RECHAZARSE.', 'Interpretación de TIR', 'TIR < k → Rechazar'),
('pr-eva-004', 'proyectos_riesgo', 'evaluacion', 'basico', '¿Qué mide la razón beneficio-costo?', 'La utilidad neta', 'La relación entre el valor presente de beneficios y costos', 'El margen de ganancia', 'El período de recuperación', 'b', 'La razón B/C compara el VP de los beneficios con el VP de los costos. Si B/C > 1, los beneficios superan los costos y el proyecto es viable.', 'Razón Beneficio-Costo', 'B/C = VP Beneficios / VP Costos'),
('pr-flu-001', 'proyectos_riesgo', 'flujos', 'basico', '¿Qué son los flujos de caja incrementales?', 'Los flujos totales de la empresa', 'Los flujos que CAMBIAN debido al proyecto', 'Los flujos históricos', 'Los flujos de competidores', 'b', 'Los flujos incrementales son los flujos que CAMBIAN como resultado de aceptar el proyecto. Solo los flujos que el proyecto genera o evita son relevantes para la decisión.', 'Flujos Incrementales', 'Solo flujos que cambian con el proyecto'),
('pr-flu-002', 'proyectos_riesgo', 'flujos', 'intermedio', '¿Los costos hundidos deben incluirse en la evaluación de proyectos?', 'Sí, siempre', 'No, porque ya ocurrieron y no pueden recuperarse', 'Solo si son grandes', 'Depende del proyecto', 'b', 'Los costos hundidos (sunk costs) son irrecuperables independientemente de la decisión futura. NO deben incluirse porque no son flujos incrementales; la decisión no los afecta.', 'Costos Hundidos', 'Sunk costs: NO incluir'),
('pr-flu-003', 'proyectos_riesgo', 'flujos', 'avanzado', '¿Qué es el costo de oportunidad en evaluación de proyectos?', 'El costo de los materiales', 'El beneficio sacrificado al no usar recursos en su mejor alternativa', 'El costo de financiamiento', 'El costo de mano de obra', 'b', 'El costo de oportunidad es el valor de la mejor alternativa NO elegida. Si usas un terreno propio para el proyecto, debes incluir como costo lo que ganarías vendiéndolo o rentándolo.', 'Costo de Oportunidad', 'Beneficio de la mejor alternativa sacrificada');

-- MÓDULO 4: COSTOS Y NORMAS (NIF) - 100 preguntas
INSERT INTO preguntas (id, modulo, subtema, nivel, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, tema, formula) VALUES

-- Postulados Básicos NIF
('cn-pos-001', 'costos_normas', 'postulados', 'basico', '¿Qué establece el postulado de Sustancia Económica?', 'La forma legal prevalece sobre la realidad', 'La realidad económica prevalece sobre la forma jurídica', 'Solo importan los documentos legales', 'La contabilidad es opcional', 'b', 'El postulado de SUSTANCIA ECONÓMICA establece que debe prevalecer la realidad económica de las transacciones sobre su forma legal o jurídica. Esencia sobre forma.', 'Postulados Básicos NIF', 'Sustancia > Forma'),
('cn-pos-002', 'costos_normas', 'postulados', 'basico', '¿Qué significa el postulado de Negocio en Marcha?', 'La empresa cerrará pronto', 'La entidad tiene existencia permanente en un horizonte ilimitado', 'El negocio está en quiebra', 'Solo aplica a empresas grandes', 'b', 'NEGOCIO EN MARCHA asume que la entidad continuará operando indefinidamente, sin intención de liquidar o reducir sustancialmente sus operaciones.', 'Postulados Básicos NIF', 'Continuidad operativa asumida'),
('cn-pos-003', 'costos_normas', 'postulados', 'intermedio', '¿Cuándo se reconoce una transacción según el postulado de Devengación Contable?', 'Cuando se cobra o paga efectivo', 'Cuando la transacción afecta económicamente a la entidad', 'Cuando el contador decide', 'Al final del año fiscal', 'b', 'La DEVENGACIÓN CONTABLE establece que las transacciones se reconocen cuando afectan económicamente a la entidad, independientemente de cuándo se reciba o pague efectivo.', 'Postulados Básicos NIF', 'Reconocimiento: afectación económica'),
('cn-pos-004', 'costos_normas', 'postulados', 'intermedio', '¿Qué establece el postulado de Dualidad Económica?', 'Todo activo tiene un pasivo igual', 'Los recursos provienen de fuentes propias y ajenas', 'La contabilidad es doble', 'Hay dos tipos de empresas', 'b', 'La DUALIDAD ECONÓMICA establece que los recursos de una entidad provienen de fuentes de financiamiento: propias (capital) y ajenas (pasivo). A = P + C.', 'Postulados Básicos NIF', 'Recursos = Fuentes propias + ajenas'),
('cn-pos-005', 'costos_normas', 'postulados', 'avanzado', '¿Qué implica el postulado de Consistencia?', 'Cambiar métodos contables frecuentemente', 'Aplicar el mismo tratamiento a operaciones similares a través del tiempo', 'Usar diferentes normas cada año', 'Depende del auditor', 'b', 'La CONSISTENCIA requiere que operaciones similares reciban el mismo tratamiento contable a través del tiempo, permitiendo comparabilidad. Cambios deben justificarse y revelarse.', 'Postulados Básicos NIF', 'Tratamiento uniforme en el tiempo'),
('cn-pos-006', 'costos_normas', 'postulados', 'basico', '¿Qué es una Entidad Económica según las NIF?', 'Solo empresas grandes', 'Una unidad identificable con control centralizado que realiza actividades económicas', 'Cualquier persona física', 'Solo empresas públicas', 'b', 'La ENTIDAD ECONÓMICA es una unidad identificable que realiza actividades económicas, con recursos controlados y estructura organizacional. Es el sujeto de la contabilidad.', 'Postulados Básicos NIF', 'Entidad = unidad económica identificable'),

-- Características Cualitativas
('cn-car-001', 'costos_normas', 'caracteristicas', 'basico', '¿Cuáles son las características cualitativas primarias de la información financiera?', 'Costo y beneficio', 'Relevancia y Representación Fiel', 'Velocidad y cantidad', 'Formato y presentación', 'b', 'Las características PRIMARIAS son: RELEVANCIA (influye en decisiones) y REPRESENTACIÓN FIEL (refleja fielmente la realidad). Son indispensables.', 'Características Cualitativas', 'Primarias: Relevancia + Representación Fiel'),
('cn-car-002', 'costos_normas', 'caracteristicas', 'intermedio', '¿Qué hace que la información sea relevante?', 'Que sea detallada', 'Que influya en la toma de decisiones de los usuarios', 'Que sea antigua', 'Que incluya opiniones', 'b', 'La información es RELEVANTE cuando puede influir en las decisiones económicas de los usuarios, ya sea confirmando o corrigiendo sus expectativas previas.', 'Relevancia', 'Influye en decisiones'),
('cn-car-003', 'costos_normas', 'caracteristicas', 'intermedio', '¿Qué implica la Representación Fiel?', 'Información inventada', 'Información completa, neutral y libre de error material', 'Solo información favorable', 'Información resumida', 'b', 'La REPRESENTACIÓN FIEL requiere que la información sea: COMPLETA (incluye todo lo necesario), NEUTRAL (sin sesgo) y LIBRE DE ERROR material.', 'Representación Fiel', 'Completa + Neutral + Libre de error'),
('cn-car-004', 'costos_normas', 'caracteristicas', 'avanzado', '¿Cuáles son características secundarias de la información financiera?', 'Relevancia y confiabilidad', 'Comparabilidad, Verificabilidad, Oportunidad y Comprensibilidad', 'Solo la oportunidad', 'Ninguna de las anteriores', 'b', 'Las características SECUNDARIAS mejoran la utilidad de la información: Comparabilidad (entre periodos/entidades), Verificabilidad (comprobable), Oportunidad (a tiempo), Comprensibilidad (entendible).', 'Características Secundarias', 'Comparabilidad, Verificabilidad, Oportunidad, Comprensibilidad'),

-- Elementos de Estados Financieros
('cn-ele-001', 'costos_normas', 'elementos', 'basico', '¿Qué es un Activo según las NIF?', 'Solo el efectivo', 'Recurso controlado resultado de eventos pasados del que se esperan beneficios futuros', 'Cualquier cosa de valor', 'Solo propiedades', 'b', 'Un ACTIVO es un recurso económico controlado por la entidad, resultado de eventos pasados, del que se esperan beneficios económicos futuros. Control, no necesariamente propiedad legal.', 'Definición de Activo', 'Recurso controlado + beneficios futuros'),
('cn-ele-002', 'costos_normas', 'elementos', 'basico', '¿Qué es un Pasivo según las NIF?', 'Dinero en el banco', 'Obligación presente resultado de eventos pasados que implica transferir recursos', 'Inversiones de la empresa', 'Capital de los socios', 'b', 'Un PASIVO es una obligación presente de la entidad, surgida de eventos pasados, cuya liquidación se espera que resulte en salida de recursos con beneficios económicos.', 'Definición de Pasivo', 'Obligación presente + transferir recursos'),
('cn-ele-003', 'costos_normas', 'elementos', 'intermedio', '¿Qué es el Capital Contable?', 'Las deudas de la empresa', 'El valor residual de los activos después de deducir pasivos', 'Solo las acciones emitidas', 'El efectivo disponible', 'b', 'El CAPITAL CONTABLE es el valor residual de los activos después de deducir todos los pasivos. Representa la participación de los propietarios en la entidad. A - P = C.', 'Definición de Capital', 'Capital = Activos - Pasivos'),
('cn-ele-004', 'costos_normas', 'elementos', 'intermedio', '¿Qué son los Ingresos según las NIF?', 'Solo las ventas', 'Incrementos en beneficios económicos que aumentan el capital (excepto aportaciones)', 'Cualquier entrada de dinero', 'Las cuentas por cobrar', 'b', 'Los INGRESOS son incrementos en los beneficios económicos durante el periodo que producen aumentos en el capital, distintos de aportaciones de los propietarios.', 'Definición de Ingresos', 'Incremento de beneficios → ↑Capital'),
('cn-ele-005', 'costos_normas', 'elementos', 'intermedio', '¿Qué son los Gastos según las NIF?', 'Solo los salarios', 'Decrementos en beneficios económicos que disminuyen el capital (excepto distribuciones)', 'Las compras de activos', 'Los pagos a proveedores', 'b', 'Los GASTOS son decrementos en los beneficios económicos durante el periodo que producen disminuciones en el capital, distintos de distribuciones a los propietarios.', 'Definición de Gastos', 'Decremento de beneficios → ↓Capital'),

-- Juicio Profesional
('cn-jui-001', 'costos_normas', 'juicio', 'avanzado', '¿Qué es el Juicio Profesional en contabilidad?', 'La opinión personal del contador', 'Selección de cursos de acción bajo incertidumbre usando conocimiento técnico y experiencia', 'Ignorar las normas cuando convenga', 'Hacer lo que pida el cliente', 'b', 'El JUICIO PROFESIONAL es el empleo de conocimientos técnicos y experiencia necesarios para seleccionar cursos de acción bajo incertidumbre, dentro del marco normativo.', 'Juicio Profesional', 'Conocimiento + Experiencia + Marco normativo'),
('cn-jui-002', 'costos_normas', 'juicio', 'avanzado', '¿Cuándo se requiere mayor juicio profesional?', 'Cuando las normas son claras', 'Cuando existe incertidumbre o las normas permiten alternativas', 'Nunca se requiere', 'Solo en empresas grandes', 'b', 'El juicio profesional es más necesario cuando: hay incertidumbre en la medición, las normas permiten alternativas de tratamiento, o no existe norma específica aplicable.', 'Aplicación del Juicio', 'Mayor incertidumbre → Mayor juicio'),

-- Marco Normativo
('cn-mar-001', 'costos_normas', 'marco', 'basico', '¿Qué significa CINIF?', 'Consejo Internacional de Normas', 'Consejo Mexicano de Normas de Información Financiera', 'Comité de Impuestos', 'Centro de Investigación Financiera', 'b', 'CINIF es el Consejo Mexicano de Normas de Información Financiera, A.C., organismo emisor de las NIF en México.', 'Organismos Normativos', 'CINIF: emisor de NIF en México'),
('cn-mar-002', 'costos_normas', 'marco', 'intermedio', '¿Qué es la supletoriedad en las NIF?', 'Aplicar cualquier norma', 'Aplicar normas alternas cuando no existe NIF específica', 'Ignorar las NIF', 'Crear normas propias', 'b', 'La SUPLETORIEDAD permite aplicar normas de otros marcos normativos (como IFRS) cuando no existe una NIF específica que regule una transacción o evento particular.', 'Supletoriedad', 'Usar normas alternas si no hay NIF'),
('cn-mar-003', 'costos_normas', 'marco', 'basico', '¿Qué es una INIF?', 'Una norma internacional', 'Una Interpretación a las Normas de Información Financiera', 'Un impuesto', 'Una institución financiera', 'b', 'Las INIF (Interpretaciones a las NIF) aclaran o amplían temas establecidos en las NIF, o proporcionan guía sobre problemas de aplicación.', 'INIF', 'Interpretaciones que aclaran las NIF'),

-- Valuación y Reconocimiento
('cn-val-001', 'costos_normas', 'valuacion', 'intermedio', '¿Qué es el costo histórico?', 'El costo futuro estimado', 'El monto de efectivo pagado o el valor razonable de la contraprestación al adquirir un activo', 'El costo de reemplazo', 'El valor de mercado actual', 'b', 'El COSTO HISTÓRICO es el monto de efectivo o equivalentes pagado, o el valor razonable de la contraprestación entregada al momento de adquirir un activo.', 'Bases de Valuación', 'Costo histórico: valor al momento de adquisición'),
('cn-val-002', 'costos_normas', 'valuacion', 'avanzado', '¿Qué es el Valor Razonable?', 'El costo original', 'El precio que se recibiría por vender un activo en una transacción ordenada entre participantes del mercado', 'El valor contable', 'El costo de reemplazo', 'b', 'El VALOR RAZONABLE es el precio que se recibiría por vender un activo (o pagar un pasivo) en una transacción ordenada entre participantes del mercado en la fecha de medición.', 'Valor Razonable', 'Precio de salida en mercado ordenado'),
('cn-val-003', 'costos_normas', 'valuacion', 'intermedio', '¿Cuándo se reconoce inicialmente un activo?', 'Cuando el contador decide', 'Cuando es probable que fluyan beneficios futuros y su valor puede medirse confiablemente', 'Solo al final del año', 'Cuando se paga completamente', 'b', 'Un activo se RECONOCE cuando: 1) es probable que fluyan beneficios económicos futuros a la entidad, y 2) su valor puede medirse confiablemente.', 'Criterios de Reconocimiento', 'Beneficios probables + Medición confiable'),

-- Presentación Razonable
('cn-pre-001', 'costos_normas', 'presentacion', 'basico', '¿Qué es la Presentación Razonable?', 'Presentar solo lo favorable', 'Cumplimiento cabal de las NIF para reflejar fielmente la situación financiera', 'Simplificar la información', 'Ocultar información negativa', 'b', 'La PRESENTACIÓN RAZONABLE implica el cumplimiento cabal de las NIF para que los estados financieros reflejen fielmente la situación, desempeño y flujos de efectivo de la entidad.', 'Presentación Razonable', 'Cumplimiento NIF + Reflejo fiel'),

-- Más preguntas de Costos y Normas
('cn-pos-007', 'costos_normas', 'postulados', 'avanzado', '¿Qué es la Asociación de Costos y Gastos con Ingresos?', 'Registrar todo al mismo tiempo', 'Los costos y gastos deben identificarse con el ingreso que generan en el mismo periodo', 'Separar costos de gastos', 'Diferir todos los gastos', 'b', 'La ASOCIACIÓN (matching) requiere que los costos y gastos se reconozcan en el mismo periodo que los ingresos que ayudaron a generar. Correlación entre esfuerzos y logros.', 'Asociación', 'Costos/Gastos ↔ Ingresos del periodo'),
('cn-car-005', 'costos_normas', 'caracteristicas', 'basico', '¿Por qué es importante la Comparabilidad?', 'Para impresionar a los usuarios', 'Para que los usuarios puedan identificar similitudes y diferencias entre entidades y periodos', 'Solo es un requisito legal', 'No es importante', 'b', 'La COMPARABILIDAD permite a los usuarios identificar similitudes y diferencias: entre diferentes entidades (comparación horizontal) y entre periodos de la misma entidad (comparación temporal).', 'Comparabilidad', 'Identificar similitudes y diferencias'),
('cn-ele-006', 'costos_normas', 'elementos', 'avanzado', '¿Qué distingue una Utilidad Integral de la Utilidad Neta tradicional?', 'Son lo mismo', 'La Utilidad Integral incluye partidas que no pasan por resultados pero afectan el capital', 'La Integral es menor', 'La Neta es más completa', 'b', 'La UTILIDAD INTEGRAL incluye la utilidad neta MÁS otras partidas que afectan directamente el capital sin pasar por el estado de resultados (ORI), como ajustes por conversión cambiaria.', 'Utilidad Integral', 'Utilidad Neta + ORI'),
('cn-val-004', 'costos_normas', 'valuacion', 'avanzado', '¿Qué es el deterioro de un activo?', 'Su destrucción física', 'Cuando el valor en libros excede su valor recuperable', 'Su venta', 'Su depreciación normal', 'b', 'El DETERIORO ocurre cuando el valor en libros de un activo supera su valor recuperable (mayor entre valor de uso y valor razonable menos costos de venta). Debe reconocerse pérdida.', 'Deterioro de Activos', 'Deterioro: Valor libros > Valor recuperable');

-- MÓDULO 5: IMPUESTOS Y LEYES (100 preguntas)
INSERT INTO preguntas (id, modulo, subtema, nivel, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, tema, formula) VALUES

-- IVA Básico
('il-iva-001', 'impuestos_leyes', 'iva', 'basico', '¿Qué significa IVA?', 'Impuesto al Valor Adquirido', 'Impuesto al Valor Agregado', 'Impuesto Variable Anual', 'Impuesto sobre Ventas Acumuladas', 'b', 'IVA significa Impuesto al Valor Agregado. Grava el valor que se agrega en cada etapa de producción y comercialización, evitando la acumulación de impuesto.', 'Conceptos Básicos IVA', 'IVA = Impuesto al Valor Agregado'),
('il-iva-002', 'impuestos_leyes', 'iva', 'basico', '¿Cuál es la tasa general del IVA en México?', '10%', '15%', '16%', '21%', 'c', 'La tasa general del IVA en México es del 16%. Existe también tasa 0% para ciertos bienes y exención para otros.', 'Tasas de IVA', 'Tasa general: 16%'),
('il-iva-003', 'impuestos_leyes', 'iva', 'basico', '¿Qué es el IVA Trasladado?', 'El IVA que paga el contribuyente a sus proveedores', 'El IVA que el contribuyente cobra a sus clientes', 'El IVA que se paga al SAT', 'El IVA de importaciones', 'b', 'El IVA TRASLADADO es el impuesto que el contribuyente cobra a sus clientes al vender bienes o prestar servicios. Es el IVA que "traslada" a sus compradores.', 'IVA Trasladado', 'IVA cobrado a clientes'),
('il-iva-004', 'impuestos_leyes', 'iva', 'basico', '¿Qué es el IVA Acreditable?', 'El IVA que se paga al SAT', 'El IVA pagado a proveedores que puede restarse del IVA trasladado', 'El IVA de exportaciones', 'El IVA exento', 'b', 'El IVA ACREDITABLE es el IVA que el contribuyente pagó a sus proveedores y que puede restar (acreditar) del IVA que cobró a sus clientes.', 'IVA Acreditable', 'IVA pagado a proveedores'),
('il-iva-005', 'impuestos_leyes', 'iva', 'intermedio', 'Una empresa cobra $100,000 de IVA a clientes y paga $70,000 de IVA a proveedores. ¿Cuánto debe pagar al SAT?', '$170,000', '$70,000', '$30,000', '$100,000', 'c', 'IVA a pagar = IVA Trasladado - IVA Acreditable = 100,000 - 70,000 = $30,000. La empresa solo paga la diferencia al SAT.', 'Cálculo de IVA', 'IVA a pagar = Trasladado - Acreditable'),

-- Acreditamiento de IVA
('il-acr-001', 'impuestos_leyes', 'acreditamiento', 'intermedio', '¿Qué requisitos debe cumplir el IVA para ser acreditable?', 'Solo tener factura', 'Ser estrictamente indispensable, estar efectivamente pagado y corresponder a actividades gravadas', 'Solo que sea de este año', 'Ningún requisito especial', 'b', 'Para ser acreditable, el IVA debe: 1) Corresponder a gastos estrictamente indispensables, 2) Estar efectivamente pagado, 3) Estar trasladado expresamente en comprobante, 4) Relacionarse con actividades gravadas.', 'Requisitos de Acreditamiento', 'Indispensable + Pagado + Comprobante + Gravado'),
('il-acr-002', 'impuestos_leyes', 'acreditamiento', 'avanzado', '¿Cómo se calcula el IVA acreditable cuando se tienen actividades gravadas y exentas?', 'Se acredita todo', 'Se aplica proporción: (actividades gravadas / actividades totales) × IVA pagado', 'No se puede acreditar nada', 'Solo se acredita el 50%', 'b', 'Cuando el contribuyente realiza actividades gravadas Y exentas, debe calcular la proporción de IVA acreditable: (Valor act. gravadas / Valor total actividades) × IVA pagado.', 'Proporción de Acreditamiento', 'Proporción = Gravadas / Total'),
('il-acr-003', 'impuestos_leyes', 'acreditamiento', 'intermedio', '¿Qué sucede si el IVA acreditable es mayor que el trasladado?', 'Se pierde el excedente', 'Se genera un saldo a favor que puede solicitarse en devolución o compensarse', 'Se paga de todas formas', 'Hay que corregir la contabilidad', 'b', 'Cuando IVA Acreditable > IVA Trasladado, se genera un SALDO A FAVOR. Este puede solicitarse en devolución o compensarse contra otros impuestos federales.', 'Saldo a Favor', 'Acreditable > Trasladado = Saldo a favor'),
('il-acr-004', 'impuestos_leyes', 'acreditamiento', 'avanzado', '¿Qué establece el Artículo 5-B de la Ley del IVA?', 'Las tasas del IVA', 'Permite usar la proporción del ejercicio anterior para calcular IVA acreditable mensual', 'Las exenciones del IVA', 'Las sanciones por no pagar', 'b', 'El Art. 5-B permite usar la proporción de acreditamiento del ejercicio inmediato anterior para los pagos mensuales provisionales, realizando ajuste anual.', 'Artículo 5-B LIVA', 'Proporción ejercicio anterior para pagos provisionales'),

-- ISR
('il-isr-001', 'impuestos_leyes', 'isr', 'basico', '¿Qué grava el ISR?', 'Las ventas', 'Los ingresos de las personas físicas y morales', 'Solo los salarios', 'Las importaciones', 'b', 'El ISR (Impuesto Sobre la Renta) grava los INGRESOS de las personas físicas y morales, residentes en México o con fuente de riqueza en territorio nacional.', 'Objeto del ISR', 'ISR grava ingresos'),
('il-isr-002', 'impuestos_leyes', 'isr', 'basico', '¿Cuál es la tasa de ISR para personas morales en México?', '16%', '25%', '30%', '35%', 'c', 'La tasa de ISR para personas morales (empresas) en México es del 30% sobre la utilidad fiscal.', 'Tasa ISR PM', 'Tasa ISR Personas Morales: 30%'),
('il-isr-003', 'impuestos_leyes', 'isr', 'intermedio', '¿Qué son las deducciones autorizadas en ISR?', 'Todos los gastos de la empresa', 'Los gastos que la ley permite restar de los ingresos para determinar la base gravable', 'Solo los salarios', 'Las inversiones únicamente', 'b', 'Las DEDUCCIONES AUTORIZADAS son los gastos que la Ley del ISR permite restar de los ingresos acumulables para determinar la utilidad fiscal (base del impuesto).', 'Deducciones ISR', 'Gastos permitidos por ley'),
('il-isr-004', 'impuestos_leyes', 'isr', 'intermedio', '¿Qué es la utilidad fiscal?', 'Las ventas totales', 'Ingresos acumulables menos deducciones autorizadas', 'El efectivo disponible', 'La utilidad contable', 'b', 'La UTILIDAD FISCAL = Ingresos Acumulables - Deducciones Autorizadas. Es la base sobre la cual se calcula el ISR, y puede diferir de la utilidad contable.', 'Utilidad Fiscal', 'Utilidad Fiscal = Ingresos - Deducciones'),
('il-isr-005', 'impuestos_leyes', 'isr', 'avanzado', '¿Qué es el CUFIN?', 'Un tipo de ingreso', 'Cuenta de Utilidad Fiscal Neta, utilidades ya gravadas que pueden distribuirse sin retención', 'Un gasto deducible', 'Una obligación fiscal', 'b', 'El CUFIN (Cuenta de Utilidad Fiscal Neta) registra las utilidades que ya pagaron ISR. Los dividendos provenientes del CUFIN pueden distribuirse sin retención adicional.', 'CUFIN', 'Utilidades ya gravadas con ISR'),

-- Determinación Presuntiva
('il-pre-001', 'impuestos_leyes', 'presuntiva', 'avanzado', '¿Qué es la determinación presuntiva?', 'Un cálculo exacto', 'Facultad de la autoridad para estimar ingresos cuando el contribuyente no proporciona información confiable', 'Un beneficio fiscal', 'Una deducción especial', 'b', 'La DETERMINACIÓN PRESUNTIVA es la facultad de la autoridad fiscal para ESTIMAR los ingresos y/o utilidades cuando el contribuyente no proporciona información, tiene irregularidades o se opone a la revisión.', 'Determinación Presuntiva', 'Autoridad estima cuando no hay info confiable'),
('il-pre-002', 'impuestos_leyes', 'presuntiva', 'avanzado', '¿En qué casos procede la determinación presuntiva?', 'Siempre que el SAT quiera', 'Cuando el contribuyente se opone a revisión, no tiene contabilidad o hay irregularidades graves', 'Solo para empresas grandes', 'Nunca procede', 'b', 'Procede cuando: el contribuyente se opone a revisión, no lleva contabilidad, no presenta declaraciones, o la contabilidad tiene irregularidades que impiden conocer operaciones reales.', 'Causales de Presuntiva', 'Oposición, falta de contabilidad, irregularidades'),

-- Seguro Social
('il-seg-001', 'impuestos_leyes', 'seguro_social', 'basico', '¿Qué cubre el IMSS?', 'Solo accidentes de trabajo', 'Enfermedades, maternidad, invalidez, vida, retiro, cesantía y guarderías', 'Solo jubilación', 'Solo servicios médicos', 'b', 'El IMSS proporciona seguros de: Enfermedades y Maternidad, Riesgos de Trabajo, Invalidez y Vida, Retiro/Cesantía/Vejez, y Guarderías y Prestaciones Sociales.', 'Cobertura IMSS', '5 seguros: EyM, RT, IyV, RCV, GPS'),
('il-seg-002', 'impuestos_leyes', 'seguro_social', 'intermedio', '¿Qué es el Salario Base de Cotización (SBC)?', 'Solo el salario mínimo', 'El salario diario integrado con prestaciones para calcular cuotas del IMSS', 'El salario neto', 'El salario bruto únicamente', 'b', 'El SBC es el salario diario del trabajador INTEGRADO con todas las prestaciones (aguinaldo, vacaciones, prima, etc.) que se usa como base para calcular las cuotas del IMSS.', 'Salario Base de Cotización', 'SBC = Salario + Prestaciones integradas'),
('il-seg-003', 'impuestos_leyes', 'seguro_social', 'intermedio', '¿Quién paga las cuotas del IMSS?', 'Solo el trabajador', 'Solo el patrón', 'Patrón, trabajador y gobierno, según el seguro', 'Solo el gobierno', 'c', 'Las cuotas del IMSS son TRIPARTITAS en algunos seguros: las pagan patrón, trabajador y gobierno en diferentes proporciones según el tipo de seguro.', 'Financiamiento IMSS', 'Tripartito: Patrón + Trabajador + Gobierno'),

-- Obligaciones Fiscales
('il-obl-001', 'impuestos_leyes', 'obligaciones', 'basico', '¿Qué es el RFC?', 'Registro Federal de Comercio', 'Registro Federal de Contribuyentes', 'Registro Fiscal de Cuentas', 'Reporte Financiero Contable', 'b', 'El RFC (Registro Federal de Contribuyentes) es la clave de identificación fiscal que el SAT asigna a personas físicas y morales para sus obligaciones tributarias.', 'RFC', 'RFC = identificación fiscal ante SAT'),
('il-obl-002', 'impuestos_leyes', 'obligaciones', 'basico', '¿Qué es un CFDI?', 'Un tipo de impuesto', 'Comprobante Fiscal Digital por Internet', 'Un certificado bancario', 'Un contrato fiscal', 'b', 'El CFDI (Comprobante Fiscal Digital por Internet) es la factura electrónica que ampara las operaciones comerciales y es requisito para deducir gastos.', 'CFDI', 'CFDI = Factura electrónica'),
('il-obl-003', 'impuestos_leyes', 'obligaciones', 'intermedio', '¿Cada cuándo se presentan las declaraciones mensuales de IVA?', 'Anualmente', 'A más tardar el día 17 del mes siguiente', 'Cada trimestre', 'No hay fecha límite', 'b', 'Las declaraciones mensuales de IVA deben presentarse a más tardar el día 17 del mes siguiente a aquel al que corresponda el pago.', 'Plazos de Declaración', 'IVA mensual: día 17 del mes siguiente'),

-- Gobierno Corporativo
('il-gob-001', 'impuestos_leyes', 'gobierno', 'avanzado', '¿Qué es el Gobierno Corporativo?', 'El gobierno de un país', 'Sistema de principios y prácticas para dirigir y controlar sociedades, protegiendo intereses de stakeholders', 'Solo reglas para directivos', 'Las leyes mercantiles', 'b', 'El GOBIERNO CORPORATIVO es el conjunto de principios, políticas y prácticas que rigen la dirección y control de una sociedad, buscando transparencia y protección de todos los interesados.', 'Gobierno Corporativo', 'Principios de dirección y control'),
('il-gob-002', 'impuestos_leyes', 'gobierno', 'avanzado', '¿Qué es el Reporte Integrado?', 'El estado de resultados', 'Informe que comunica cómo la estrategia de una organización conduce a creación de valor a largo plazo', 'El balance general', 'La declaración anual', 'b', 'El REPORTE INTEGRADO (del IIRC) comunica cómo la estrategia, gobierno, desempeño y perspectivas de una organización conducen a la creación de valor sostenible.', 'Reporte Integrado', 'Comunica creación de valor integral'),

-- Más preguntas de Impuestos
('il-iva-006', 'impuestos_leyes', 'iva', 'basico', '¿Qué actividades están gravadas a tasa 0% de IVA?', 'Todas las ventas', 'Alimentos no industrializados, medicinas, exportaciones', 'Ninguna actividad', 'Solo servicios', 'b', 'Tasa 0%: alimentos básicos, medicinas de patente, exportación de bienes y servicios, entre otros. El contribuyente puede acreditar el IVA pagado a sus proveedores.', 'Tasa 0% IVA', 'Alimentos, medicinas, exportaciones'),
('il-iva-007', 'impuestos_leyes', 'iva', 'intermedio', '¿Cuál es la diferencia entre tasa 0% y exención de IVA?', 'Son lo mismo', 'En tasa 0% se puede acreditar IVA pagado, en exención no', 'En exención se acredita más', 'No hay diferencia práctica', 'b', 'En TASA 0% el contribuyente SÍ puede acreditar el IVA pagado a proveedores (y pedir devolución). En EXENCIÓN NO puede acreditar el IVA pagado, lo cual representa un costo.', 'Tasa 0% vs Exención', 'Tasa 0%: acredita IVA; Exención: no acredita'),
('il-isr-006', 'impuestos_leyes', 'isr', 'avanzado', '¿Qué son los pagos provisionales de ISR?', 'Pagos finales', 'Anticipos mensuales del ISR anual, calculados sobre utilidad estimada', 'Pagos opcionales', 'Solo para personas físicas', 'b', 'Los PAGOS PROVISIONALES son anticipos mensuales del ISR anual. Se calculan aplicando coeficiente de utilidad a los ingresos y se acreditan contra el impuesto anual.', 'Pagos Provisionales', 'Anticipos mensuales de ISR anual'),
('il-isr-007', 'impuestos_leyes', 'isr', 'intermedio', '¿Qué es el coeficiente de utilidad?', 'La tasa de ISR', 'Razón utilidad fiscal / ingresos nominales del ejercicio anterior, usada para pagos provisionales', 'Un gasto deducible', 'El margen de ganancia', 'b', 'El COEFICIENTE DE UTILIDAD = Utilidad Fiscal / Ingresos del ejercicio anterior. Se aplica a los ingresos del periodo para estimar la utilidad gravable en pagos provisionales.', 'Coeficiente de Utilidad', 'CU = Utilidad Fiscal / Ingresos');

-- MÓDULO 6: DICTÁMENES Y CONTROL (100 preguntas)
INSERT INTO preguntas (id, modulo, subtema, nivel, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, tema, formula) VALUES

-- Evidencia de Auditoría (NIA 500)
('dc-evi-001', 'dictamenes_control', 'evidencia', 'basico', '¿Qué es la evidencia de auditoría?', 'Solo los estados financieros', 'La información utilizada por el auditor para alcanzar conclusiones que sustenten su opinión', 'La carta de representación', 'Los contratos del cliente', 'b', 'La EVIDENCIA DE AUDITORÍA es toda la información utilizada por el auditor para llegar a las conclusiones en las que basa su opinión sobre los estados financieros.', 'NIA 500', 'Información para sustentar la opinión'),
('dc-evi-002', 'dictamenes_control', 'evidencia', 'basico', '¿Qué mide la suficiencia de la evidencia?', 'Su calidad', 'Su cantidad (medida cuantitativa)', 'Su relevancia', 'Su costo', 'b', 'La SUFICIENCIA es la medida CUANTITATIVA de la evidencia. La cantidad necesaria depende del riesgo de error material valorado y de la calidad de la evidencia obtenida.', 'Suficiencia', 'Suficiencia = Medida cuantitativa'),
('dc-evi-003', 'dictamenes_control', 'evidencia', 'basico', '¿Qué mide la adecuación de la evidencia?', 'Su cantidad', 'Su calidad (relevancia y fiabilidad)', 'Su costo', 'Su disponibilidad', 'b', 'La ADECUACIÓN es la medida CUALITATIVA de la evidencia, es decir, su relevancia (pertinencia para la afirmación) y fiabilidad (confiabilidad de la fuente y método de obtención).', 'Adecuación', 'Adecuación = Relevancia + Fiabilidad'),
('dc-evi-004', 'dictamenes_control', 'evidencia', 'intermedio', '¿Cuándo es más fiable la evidencia de auditoría?', 'Cuando es verbal', 'Cuando proviene de fuentes externas independientes y en forma documental', 'Cuando el cliente la proporciona', 'Cuando es antigua', 'b', 'La evidencia es MÁS FIABLE cuando: 1) Proviene de fuentes externas independientes, 2) Es documental (no verbal), 3) Es original (no copia), 4) El control interno del cliente es efectivo.', 'Fiabilidad de Evidencia', 'Externa + Documental + Original = Más fiable'),
('dc-evi-005', 'dictamenes_control', 'evidencia', 'avanzado', '¿Qué debe hacer el auditor ante evidencia contradictoria?', 'Ignorarla', 'Investigar y obtener evidencia adicional hasta resolver la contradicción', 'Aceptar la del cliente', 'Emitir opinión negativa automáticamente', 'b', 'Ante EVIDENCIA CONTRADICTORIA, el auditor debe realizar procedimientos adicionales para investigar y resolver la incongruencia antes de poder concluir sobre la afirmación.', 'Evidencia Contradictoria', 'Investigar hasta resolver contradicción'),

-- Procedimientos de Auditoría
('dc-pro-001', 'dictamenes_control', 'procedimientos', 'basico', '¿Qué es la inspección como procedimiento de auditoría?', 'Revisar verbalmente', 'Examinar registros, documentos o activos físicos', 'Calcular nuevamente', 'Confirmar con terceros', 'b', 'La INSPECCIÓN implica examinar registros o documentos (internos o externos, en papel o electrónicos) o realizar examen físico de un activo.', 'Procedimientos de Auditoría', 'Inspección: examinar registros/documentos/activos'),
('dc-pro-002', 'dictamenes_control', 'procedimientos', 'basico', '¿Qué es la confirmación externa?', 'Preguntar al cliente', 'Obtener respuesta directa escrita de un tercero independiente', 'Revisar documentos', 'Calcular totales', 'b', 'La CONFIRMACIÓN EXTERNA es obtener una respuesta directa, por escrito, de un tercero (la parte confirmante), en papel o por medios electrónicos.', 'Procedimientos de Auditoría', 'Confirmación: respuesta escrita de tercero'),
('dc-pro-003', 'dictamenes_control', 'procedimientos', 'intermedio', '¿Qué es el recálculo en auditoría?', 'Revisar documentos', 'Comprobar la exactitud matemática de documentos o registros', 'Preguntar al personal', 'Observar procesos', 'b', 'El RECÁLCULO consiste en comprobar la exactitud matemática de documentos o registros. Puede realizarse manualmente o por medios electrónicos.', 'Procedimientos de Auditoría', 'Recálculo: verificar exactitud matemática'),
('dc-pro-004', 'dictamenes_control', 'procedimientos', 'intermedio', '¿Qué es la reejecución en auditoría?', 'Calcular nuevamente', 'Ejecución independiente por el auditor de procedimientos originalmente realizados como parte del control interno', 'Observar al personal', 'Confirmar saldos', 'b', 'La REEJECUCIÓN implica que el auditor ejecute independientemente procedimientos o controles que originalmente fueron realizados por el personal del cliente.', 'Procedimientos de Auditoría', 'Reejecución: repetir controles del cliente'),
('dc-pro-005', 'dictamenes_control', 'procedimientos', 'basico', '¿Qué es la indagación en auditoría?', 'Examinar documentos', 'Buscar información a través de personas informadas, dentro o fuera de la entidad', 'Confirmar con bancos', 'Observar inventarios', 'b', 'La INDAGACIÓN consiste en buscar información, financiera o no financiera, a través de personas informadas (empleados, administración, terceros). Por sí sola generalmente es insuficiente.', 'Procedimientos de Auditoría', 'Indagación: preguntar a personas informadas'),
('dc-pro-006', 'dictamenes_control', 'procedimientos', 'avanzado', '¿Por qué la indagación por sí sola es generalmente insuficiente?', 'Porque es muy costosa', 'Porque las respuestas verbales requieren corroboración con otros procedimientos', 'Porque está prohibida', 'Porque no se documenta', 'b', 'La indagación es INSUFICIENTE por sí sola porque las respuestas verbales de personas pueden estar sesgadas, ser incorrectas o incompletas. Debe corroborarse con otra evidencia.', 'Limitaciones de Indagación', 'Verbal → requiere corroboración'),

-- Control Interno (COSO)
('dc-cos-001', 'dictamenes_control', 'coso', 'basico', '¿Qué es el Marco COSO?', 'Una norma de auditoría', 'Un marco de referencia para diseñar, implementar y evaluar el control interno', 'Un tipo de dictamen', 'Una ley fiscal', 'b', 'El Marco COSO es un modelo internacionalmente reconocido para diseñar, implementar, conducir y evaluar el control interno en las organizaciones.', 'Marco COSO', 'COSO: marco de control interno'),
('dc-cos-002', 'dictamenes_control', 'coso', 'intermedio', '¿Cuántos componentes tiene el Marco COSO de Control Interno?', '3', '4', '5', '8', 'c', 'COSO tiene 5 componentes: 1) Ambiente de Control, 2) Evaluación de Riesgos, 3) Actividades de Control, 4) Información y Comunicación, 5) Supervisión y Monitoreo.', 'Componentes COSO', '5 componentes de control interno'),
('dc-cos-003', 'dictamenes_control', 'coso', 'intermedio', '¿Qué es el Ambiente de Control?', 'Los controles físicos', 'El conjunto de normas, procesos y estructuras que proporcionan la base para el control interno', 'Los sistemas de información', 'La auditoría interna únicamente', 'b', 'El AMBIENTE DE CONTROL es la base de los demás componentes. Incluye la integridad y valores éticos, compromiso de competencia, filosofía de la dirección y estilo operativo.', 'Ambiente de Control', 'Base: valores, compromiso, estilo de dirección'),
('dc-cos-004', 'dictamenes_control', 'coso', 'avanzado', '¿Qué son las actividades de control?', 'Solo la supervisión', 'Las políticas y procedimientos que ayudan a asegurar que se ejecuten las respuestas a los riesgos', 'El código de ética', 'Los reportes financieros', 'b', 'Las ACTIVIDADES DE CONTROL son las políticas y procedimientos (autorizaciones, verificaciones, conciliaciones, revisiones, segregación de funciones) que mitigan los riesgos.', 'Actividades de Control', 'Políticas y procedimientos para mitigar riesgos'),
('dc-cos-005', 'dictamenes_control', 'coso', 'avanzado', '¿Por qué es importante la segregación de funciones?', 'Para reducir costos', 'Para evitar que una persona tenga control sobre todas las fases de una transacción', 'Para aumentar la velocidad', 'No es importante', 'b', 'La SEGREGACIÓN DE FUNCIONES evita que una sola persona pueda cometer y ocultar errores o fraudes. Separa: autorización, custodia, registro y conciliación.', 'Segregación de Funciones', 'Separar: autorización, custodia, registro'),

-- Dictámenes
('dc-dic-001', 'dictamenes_control', 'dictamen', 'basico', '¿Qué es el dictamen del auditor?', 'Un informe de impuestos', 'La opinión escrita del auditor sobre los estados financieros', 'Un contrato de servicios', 'El estado de resultados', 'b', 'El DICTAMEN es el documento que contiene la opinión escrita del auditor independiente respecto a si los estados financieros están presentados razonablemente conforme al marco aplicable.', 'Dictamen de Auditoría', 'Opinión escrita del auditor'),
('dc-dic-002', 'dictamenes_control', 'dictamen', 'intermedio', '¿Cuántos tipos de opinión puede emitir el auditor?', '2', '3', '4', '5', 'c', 'El auditor puede emitir 4 tipos de opinión: 1) No modificada (limpia), 2) Con salvedades, 3) Negativa (adversa), 4) Abstención de opinión.', 'Tipos de Opinión', '4 tipos: limpia, con salvedades, adversa, abstención'),
('dc-dic-003', 'dictamenes_control', 'dictamen', 'intermedio', '¿Cuándo se emite una opinión con salvedades?', 'Cuando todo está bien', 'Cuando existen errores materiales pero no generalizados, o limitación al alcance no generalizada', 'Cuando hay fraude', 'Cuando el auditor no quiere opinar', 'b', 'Se emite opinión CON SALVEDADES cuando: 1) Hay errores materiales pero NO generalizados, o 2) No se pudo obtener evidencia suficiente pero el efecto potencial NO es generalizado.', 'Opinión con Salvedades', 'Error material o limitación NO generalizada'),
('dc-dic-004', 'dictamenes_control', 'dictamen', 'avanzado', '¿Cuándo se emite una opinión negativa (adversa)?', 'Cuando hay salvedades menores', 'Cuando los errores son materiales Y generalizados (estados financieros no confiables)', 'Cuando el auditor está cansado', 'Nunca se emite', 'b', 'Se emite opinión ADVERSA cuando el auditor concluye que los errores son MATERIALES y GENERALIZADOS (afectan a los estados financieros en su conjunto de manera significativa).', 'Opinión Adversa', 'Errores materiales Y generalizados'),
('dc-dic-005', 'dictamenes_control', 'dictamen', 'avanzado', '¿Cuándo se emite abstención de opinión?', 'Cuando todo está bien', 'Cuando no se pudo obtener evidencia suficiente y el efecto potencial es material Y generalizado', 'Cuando hay salvedades', 'Por decisión del cliente', 'b', 'Se emite ABSTENCIÓN cuando el auditor no pudo obtener evidencia suficiente y apropiada, y los posibles efectos de las incorrecciones no detectadas podrían ser MATERIALES Y GENERALIZADOS.', 'Abstención de Opinión', 'Sin evidencia suficiente + efecto potencial generalizado'),

-- Riesgos de Auditoría
('dc-rie-001', 'dictamenes_control', 'riesgo_auditoria', 'basico', '¿Qué es el riesgo de auditoría?', 'El riesgo del negocio', 'El riesgo de que el auditor emita una opinión incorrecta cuando los estados financieros tienen errores materiales', 'El riesgo de no cobrar honorarios', 'El riesgo de demanda', 'b', 'El RIESGO DE AUDITORÍA es el riesgo de que el auditor exprese una opinión de auditoría inapropiada cuando los estados financieros contienen incorrecciones materiales.', 'Riesgo de Auditoría', 'Opinión incorrecta sobre EF con errores'),
('dc-rie-002', 'dictamenes_control', 'riesgo_auditoria', 'intermedio', '¿Cuáles son los componentes del riesgo de auditoría?', 'Alto, medio y bajo', 'Riesgo inherente, riesgo de control y riesgo de detección', 'Interno y externo', 'Financiero y operativo', 'b', 'El riesgo de auditoría tiene 3 componentes: 1) INHERENTE (susceptibilidad natural a error), 2) DE CONTROL (que el control interno no prevenga/detecte), 3) DE DETECCIÓN (que el auditor no detecte).', 'Componentes del Riesgo', 'RA = RI × RC × RD'),
('dc-rie-003', 'dictamenes_control', 'riesgo_auditoria', 'avanzado', '¿Cuál es el único riesgo que el auditor puede controlar directamente?', 'El riesgo inherente', 'El riesgo de control', 'El riesgo de detección', 'Ninguno', 'c', 'El auditor SOLO puede controlar el RIESGO DE DETECCIÓN mediante la naturaleza, oportunidad y extensión de sus procedimientos. El riesgo inherente y de control dependen del cliente.', 'Control del Riesgo', 'Auditor controla: Riesgo de Detección'),
('dc-rie-004', 'dictamenes_control', 'riesgo_auditoria', 'intermedio', '¿Qué es el riesgo inherente?', 'Riesgo del auditor', 'Susceptibilidad de una afirmación a error material antes de considerar controles', 'Riesgo de no detectar errores', 'Riesgo del negocio', 'b', 'El RIESGO INHERENTE es la susceptibilidad de una afirmación a contener errores materiales, suponiendo que no existen controles relacionados. Depende de la naturaleza de la cuenta.', 'Riesgo Inherente', 'Susceptibilidad natural a error, sin controles'),

-- Documentación (NIA 230)
('dc-doc-001', 'dictamenes_control', 'documentacion', 'basico', '¿Por qué es importante la documentación de auditoría?', 'Solo para archivo', 'Proporciona evidencia de la base para la opinión y que la auditoría cumplió con normas', 'Por requisito del cliente', 'No es importante', 'b', 'La DOCUMENTACIÓN proporciona: 1) Evidencia de la base para la conclusión del auditor, 2) Evidencia de que la auditoría se planeó y ejecutó conforme a NIA y requisitos legales.', 'Importancia de Documentación', 'Evidencia de base para opinión + cumplimiento NIA'),
('dc-doc-002', 'dictamenes_control', 'documentacion', 'intermedio', '¿Qué debe contener la documentación de auditoría?', 'Solo el dictamen final', 'Naturaleza, oportunidad y extensión de procedimientos, resultados y evidencia significativa', 'Solo los estados financieros', 'Solo cartas del cliente', 'b', 'La documentación debe incluir: procedimientos realizados (naturaleza, oportunidad, extensión), resultados obtenidos, evidencia significativa, y las conclusiones alcanzadas.', 'Contenido de Documentación', 'Procedimientos + Resultados + Evidencia + Conclusiones'),
('dc-doc-003', 'dictamenes_control', 'documentacion', 'avanzado', '¿Por cuánto tiempo debe conservarse la documentación de auditoría?', '1 año', '3 años', 'Mínimo 5 años o según regulación aplicable', '10 años', 'c', 'La documentación debe conservarse por un período suficiente para cumplir requisitos legales y profesionales, generalmente MÍNIMO 5 AÑOS desde la fecha del dictamen, o más si la regulación lo exige.', 'Conservación de Documentación', 'Mínimo 5 años desde dictamen'),

-- Expertos
('dc-exp-001', 'dictamenes_control', 'expertos', 'avanzado', '¿Qué es un experto del auditor?', 'Cualquier empleado del auditor', 'Persona con competencia en un campo distinto a contabilidad/auditoría cuyo trabajo usa el auditor', 'El cliente', 'El socio del despacho', 'b', 'Un EXPERTO DEL AUDITOR es una persona u organización con competencia en un campo distinto a contabilidad/auditoría (valuación, actuarial, legal, etc.), cuyo trabajo usa el auditor.', 'Uso de Expertos', 'Especialista en campo distinto a contabilidad'),
('dc-exp-002', 'dictamenes_control', 'expertos', 'avanzado', '¿La responsabilidad de la opinión cambia cuando el auditor usa trabajo de un experto?', 'Sí, el experto es responsable', 'No, el auditor sigue siendo responsable de su opinión', 'La responsabilidad es compartida', 'Depende del contrato', 'b', 'El uso del trabajo de un experto NO reduce la responsabilidad del auditor por su opinión. El auditor debe evaluar la competencia, capacidad y objetividad del experto y evaluar la adecuación de su trabajo.', 'Responsabilidad con Expertos', 'Auditor mantiene responsabilidad total'),

-- Ley Federal del Trabajo
('dc-lft-001', 'dictamenes_control', 'laboral', 'basico', '¿Qué es el salario diario según la LFT?', 'El sueldo mensual', 'El promedio de percepciones de los últimos 30 días efectivamente trabajados', 'El salario mínimo', 'Solo el sueldo base', 'b', 'El SALARIO DIARIO según el Art. 89 de la LFT es el promedio de las percepciones obtenidas en los últimos 30 días efectivamente trabajados, incluyendo prestaciones en especie.', 'Salario Diario LFT', 'Promedio percepciones últimos 30 días'),
('dc-lft-002', 'dictamenes_control', 'laboral', 'intermedio', '¿Cómo se calcula el aguinaldo proporcional?', 'Salario × 15 días', '(Días trabajados / 365) × aguinaldo correspondiente', 'Salario × días trabajados', 'No hay aguinaldo proporcional', 'b', 'El AGUINALDO PROPORCIONAL se calcula: (Días trabajados en el año / 365) × Monto de aguinaldo anual. El mínimo legal es 15 días de salario.', 'Aguinaldo Proporcional', '(Días trabajados / 365) × Aguinaldo anual'),
('dc-lft-003', 'dictamenes_control', 'laboral', 'intermedio', '¿Cuál es el mínimo de días de aguinaldo según la LFT?', '10 días', '15 días', '20 días', '30 días', 'b', 'El aguinaldo mínimo según el Art. 87 de la LFT es de 15 DÍAS de salario, que debe pagarse antes del 20 de diciembre de cada año.', 'Aguinaldo Mínimo', 'Mínimo: 15 días de salario'),
('dc-lft-004', 'dictamenes_control', 'laboral', 'avanzado', '¿Qué es la prima de antigüedad?', 'Un bono anual', 'Prestación equivalente a 12 días de salario por cada año de servicios al terminar la relación laboral', 'El aguinaldo', 'Las vacaciones', 'b', 'La PRIMA DE ANTIGÜEDAD es el pago de 12 días de salario por cada año de servicios. Se paga al terminar la relación laboral por: retiro voluntario (15+ años), despido, muerte o incapacidad.', 'Prima de Antigüedad', '12 días de salario por año de servicio'),

-- Más preguntas de Auditoría
('dc-evi-006', 'dictamenes_control', 'evidencia', 'intermedio', '¿Qué son los registros contables como fuente de evidencia?', 'Solo los estados financieros', 'Asientos, documentos de soporte, cálculos, conciliaciones y otros registros subyacentes', 'Las cartas del abogado', 'Los contratos únicamente', 'b', 'Los REGISTROS CONTABLES incluyen: asientos iniciales y de soporte, documentación de origen, cálculos, conciliaciones, mayor general, auxiliares, y otros registros base de los estados financieros.', 'Registros Contables', 'Asientos + Documentos + Cálculos + Conciliaciones'),
('dc-pro-007', 'dictamenes_control', 'procedimientos', 'avanzado', '¿Qué son los procedimientos analíticos?', 'Revisar contratos', 'Evaluaciones de información financiera mediante análisis de relaciones plausibles entre datos', 'Confirmar saldos', 'Contar inventarios', 'b', 'Los PROCEDIMIENTOS ANALÍTICOS consisten en evaluar información financiera mediante el análisis de relaciones plausibles entre datos financieros y no financieros (ratios, tendencias, comparaciones).', 'Procedimientos Analíticos', 'Análisis de relaciones entre datos'),
('dc-cos-006', 'dictamenes_control', 'coso', 'intermedio', '¿Qué es la supervisión y monitoreo en COSO?', 'Solo la auditoría externa', 'Proceso para evaluar la calidad del funcionamiento del control interno a lo largo del tiempo', 'El presupuesto anual', 'Las ventas', 'b', 'La SUPERVISIÓN Y MONITOREO son actividades para evaluar si los componentes del control interno están presentes y funcionando adecuadamente a lo largo del tiempo.', 'Monitoreo COSO', 'Evaluar funcionamiento continuo del CI'),
('dc-mat-001', 'dictamenes_control', 'materialidad', 'intermedio', '¿Qué es la materialidad en auditoría?', 'La cantidad de trabajo', 'El importe o importes que el auditor considera que podrían influir en las decisiones de los usuarios', 'El tamaño de la empresa', 'El costo de la auditoría', 'b', 'La MATERIALIDAD es el importe que, en juicio del auditor, si se omite o presenta incorrectamente, podría razonablemente esperarse que influya en las decisiones económicas de los usuarios.', 'Materialidad', 'Importe que influye en decisiones'),
('dc-mat-002', 'dictamenes_control', 'materialidad', 'avanzado', '¿Qué es la materialidad de ejecución?', 'La materialidad final', 'Importe menor que la materialidad para los EF en conjunto, para reducir probabilidad de errores no detectados', 'Solo para procedimientos sustantivos', 'No existe tal concepto', 'b', 'La MATERIALIDAD DE EJECUCIÓN es un importe inferior a la materialidad de los EF en conjunto, establecido para reducir a un nivel apropiadamente bajo la probabilidad de que errores no corregidos excedan la materialidad.', 'Materialidad de Ejecución', 'Menor que materialidad total, reduce riesgo');

-- MÓDULO 3: ECONOMÍA INTERNACIONAL Y PEDAGÓGICA (ajustado al contenido real)
INSERT INTO preguntas (id, modulo, subtema, nivel, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, tema, formula) VALUES

-- Estructura EGEL Plus
('ei-ege-001', 'internacional', 'egel', 'basico', '¿Qué significa EGEL?', 'Examen General Educativo Latinoamericano', 'Examen General para el Egreso de la Licenciatura', 'Evaluación General de Egresados', 'Examen Global de Educación', 'b', 'EGEL significa Examen General para el Egreso de la Licenciatura, aplicado por Ceneval para evaluar conocimientos y habilidades de egresados universitarios.', 'EGEL Plus', 'Examen General para el Egreso de la Licenciatura'),
('ei-ege-002', 'internacional', 'egel', 'basico', '¿Qué organismo aplica el EGEL?', 'SEP', 'Ceneval', 'INEGI', 'CONACYT', 'b', 'El CENEVAL (Centro Nacional de Evaluación para la Educación Superior, A.C.) es el organismo responsable de diseñar y aplicar el EGEL.', 'Ceneval', 'Centro Nacional de Evaluación'),
('ei-ege-003', 'internacional', 'egel', 'intermedio', '¿Cuántos reactivos tiene aproximadamente la sección disciplinar del EGEL Plus?', '60', '100', '140', '200', 'c', 'La sección DISCIPLINAR del EGEL Plus consta de aproximadamente 140 reactivos que evalúan los conocimientos específicos de la carrera profesional.', 'Estructura EGEL', 'Sección disciplinar: ~140 reactivos'),
('ei-ege-004', 'internacional', 'egel', 'intermedio', '¿Qué evalúa la sección transversal del EGEL?', 'Solo matemáticas', 'Habilidades de lenguaje: comprensión lectora y redacción indirecta', 'Solo conocimientos técnicos', 'Historia y geografía', 'b', 'La sección TRANSVERSAL evalúa habilidades de lenguaje y comunicación: comprensión lectora y redacción indirecta, con aproximadamente 60 reactivos.', 'Sección Transversal', 'Comprensión lectora + Redacción indirecta'),
('ei-ege-005', 'internacional', 'egel', 'basico', '¿Qué porcentaje aproximado de reactivos son piloto (no cuentan)?', '5%', '15%', '25%', '0%', 'b', 'Aproximadamente el 15% de los reactivos son PILOTO, es decir, están en fase de prueba y no cuentan para la calificación final del sustentante.', 'Reactivos Piloto', '~15% reactivos de prueba'),

-- Evaluación Criterial
('ei-eva-001', 'internacional', 'evaluacion', 'intermedio', '¿Qué es la evaluación criterial?', 'Comparar estudiantes entre sí', 'Comparar el desempeño contra estándares preestablecidos', 'Evaluar solo lo memorizado', 'Dar calificaciones subjetivas', 'b', 'La evaluación CRITERIAL compara el desempeño del sustentante contra ESTÁNDARES o criterios preestablecidos, no contra otros sustentantes. Define si cumple o no con el perfil esperado.', 'Evaluación Criterial', 'Comparación contra estándares'),
('ei-eva-002', 'internacional', 'evaluacion', 'avanzado', '¿Qué niveles de desempeño puede obtener un sustentante en el EGEL?', 'Aprobado o reprobado', 'Aún No Satisfactorio, Satisfactorio, Sobresaliente', 'Excelente, Bueno, Regular, Malo', 'Solo numérico', 'b', 'Los niveles de desempeño son: ANS (Aún No Satisfactorio), DS (Desempeño Satisfactorio) y DSS (Desempeño Sobresaliente o Desempeño Satisfactorio con Sobresaliente en algún área).', 'Niveles de Desempeño', 'ANS, DS, DSS'),

-- Planeación Didáctica
('ei-did-001', 'internacional', 'didactica', 'basico', '¿Qué es la planeación didáctica?', 'Solo el temario', 'Proceso de diseño de actividades considerando intencionalidad, aprendizajes esperados y estrategias', 'El calendario escolar', 'La lista de asistencia', 'b', 'La PLANEACIÓN DIDÁCTICA es el proceso de diseñar intencionalmente las actividades de enseñanza-aprendizaje, considerando objetivos, contenidos, estrategias, recursos y evaluación.', 'Planeación Didáctica', 'Diseño intencional de actividades de E-A'),
('ei-did-002', 'internacional', 'didactica', 'intermedio', '¿Qué son los aprendizajes esperados?', 'Lo que el maestro enseña', 'Los conocimientos, habilidades y actitudes que el alumno debe lograr al final del proceso', 'Los libros de texto', 'El examen final', 'b', 'Los APRENDIZAJES ESPERADOS describen lo que el estudiante debe saber, saber hacer y saber ser al concluir un proceso educativo. Son la meta de la planeación didáctica.', 'Aprendizajes Esperados', 'Conocimientos + Habilidades + Actitudes'),
('ei-did-003', 'internacional', 'didactica', 'avanzado', '¿Qué es una secuencia didáctica?', 'Una lista de temas', 'Organización ordenada de actividades de apertura, desarrollo y cierre para lograr aprendizajes', 'El horario de clases', 'Un examen', 'b', 'Una SECUENCIA DIDÁCTICA es la organización de actividades de aprendizaje en momentos: apertura (diagnóstico, motivación), desarrollo (construcción) y cierre (síntesis, evaluación).', 'Secuencia Didáctica', 'Apertura → Desarrollo → Cierre'),

-- Investigación Educativa
('ei-inv-001', 'internacional', 'investigacion', 'basico', '¿Cuáles son los paradigmas de investigación educativa?', 'Solo cuantitativo', 'Cuantitativo, cualitativo y mixto', 'Solo cualitativo', 'Experimental únicamente', 'b', 'Los tres paradigmas principales son: CUANTITATIVO (medición numérica), CUALITATIVO (comprensión de significados) y MIXTO (combina ambos enfoques).', 'Paradigmas de Investigación', 'Cuantitativo + Cualitativo + Mixto'),
('ei-inv-002', 'internacional', 'investigacion', 'intermedio', '¿Qué caracteriza a la investigación cuantitativa?', 'Interpretación de significados', 'Medición numérica, análisis estadístico y generalización de resultados', 'Observación participante', 'Análisis de narrativas', 'b', 'La investigación CUANTITATIVA se caracteriza por: variables medibles, recolección de datos numéricos, análisis estadístico, hipótesis comprobables y generalización de resultados.', 'Investigación Cuantitativa', 'Medición + Estadística + Generalización'),
('ei-inv-003', 'internacional', 'investigacion', 'intermedio', '¿Qué caracteriza a la investigación cualitativa?', 'Solo encuestas', 'Comprensión profunda de fenómenos desde la perspectiva de los participantes', 'Experimentos controlados', 'Muestras grandes', 'b', 'La investigación CUALITATIVA busca comprender fenómenos desde la perspectiva de los participantes, usando entrevistas, observación y análisis de significados.', 'Investigación Cualitativa', 'Comprensión profunda de significados'),

-- Orientación Educativa
('ei-ori-001', 'internacional', 'orientacion', 'basico', '¿Qué es la orientación educativa?', 'Solo elegir carrera', 'Proceso de apoyo al estudiante para su desarrollo integral: académico, personal y vocacional', 'Las tutorías', 'El servicio social', 'b', 'La ORIENTACIÓN EDUCATIVA es un proceso de apoyo al estudiante que abarca aspectos académicos (rendimiento), personales (autoestima) y vocacionales (elección profesional).', 'Orientación Educativa', 'Apoyo integral: académico + personal + vocacional'),
('ei-ori-002', 'internacional', 'orientacion', 'intermedio', '¿Qué es el diagnóstico pedagógico?', 'Un examen médico', 'Proceso de identificación de necesidades, fortalezas y áreas de oportunidad del educando', 'El examen de admisión', 'La calificación final', 'b', 'El DIAGNÓSTICO PEDAGÓGICO identifica las características, necesidades, estilos de aprendizaje, fortalezas y áreas de mejora de los estudiantes para planear intervenciones adecuadas.', 'Diagnóstico Pedagógico', 'Identificación de necesidades del educando'),

-- Gestión Educativa
('ei-ges-001', 'internacional', 'gestion', 'intermedio', '¿Qué es la gestión educativa?', 'Solo administrar dinero', 'Procesos de planeación, organización, dirección y control para optimizar instituciones educativas', 'Dar clases', 'Calificar exámenes', 'b', 'La GESTIÓN EDUCATIVA aplica procesos administrativos (planeación, organización, dirección, control) para el logro de objetivos institucionales y la mejora de la calidad educativa.', 'Gestión Educativa', 'Procesos administrativos en educación'),
('ei-ges-002', 'internacional', 'gestion', 'avanzado', '¿Qué es la gestión estratégica en educación?', 'Solo el presupuesto', 'Proceso de definir misión, visión, objetivos y estrategias para el desarrollo institucional', 'El control de asistencia', 'La selección de libros', 'b', 'La GESTIÓN ESTRATÉGICA implica definir el rumbo institucional: misión (razón de ser), visión (futuro deseado), valores, objetivos estratégicos y planes de acción.', 'Gestión Estratégica', 'Misión + Visión + Objetivos estratégicos'),

-- Comprensión Lectora
('ei-lec-001', 'internacional', 'comprension', 'basico', '¿Qué es la comprensión lectora?', 'Leer rápido', 'Capacidad de identificar información, interpretar sentido y evaluar contenido de textos', 'Memorizar textos', 'Copiar párrafos', 'b', 'La COMPRENSIÓN LECTORA incluye: identificar información explícita, interpretar el sentido global del texto, relacionar ideas y evaluar críticamente el contenido.', 'Comprensión Lectora', 'Identificar + Interpretar + Evaluar'),
('ei-lec-002', 'internacional', 'comprension', 'intermedio', '¿Qué es la redacción indirecta en el contexto del EGEL?', 'Escribir un ensayo', 'Seleccionar la opción que mejor cumple con objetivos comunicativos específicos', 'Dictado', 'Copiar textos', 'b', 'La REDACCIÓN INDIRECTA evalúa la capacidad de seleccionar, entre opciones, aquella que cumple mejor con propósitos comunicativos: claridad, coherencia, adecuación al contexto.', 'Redacción Indirecta', 'Seleccionar opción con mejor comunicación'),

-- Currículo
('ei-cur-001', 'internacional', 'curriculo', 'basico', '¿Qué es el currículo educativo?', 'Solo el plan de estudios', 'Conjunto de objetivos, contenidos, métodos y criterios de evaluación de un nivel educativo', 'Los libros de texto', 'El calendario escolar', 'b', 'El CURRÍCULO es el conjunto estructurado de objetivos, contenidos, metodologías, recursos y criterios de evaluación que guían la formación en un nivel o programa educativo.', 'Currículo Educativo', 'Objetivos + Contenidos + Métodos + Evaluación'),
('ei-cur-002', 'internacional', 'curriculo', 'avanzado', '¿Qué es el currículo oculto?', 'El temario secreto', 'Aprendizajes no explícitos que se transmiten a través de las prácticas escolares', 'Temas prohibidos', 'Materias optativas', 'b', 'El CURRÍCULO OCULTO son los aprendizajes implícitos (valores, actitudes, normas) que se transmiten a través del ambiente escolar, relaciones y prácticas, sin estar formalmente escritos.', 'Currículo Oculto', 'Aprendizajes implícitos no escritos');

-- Confirmación de cantidad total
-- SELECT 'Total de preguntas insertadas en este archivo' as mensaje;
