-- ============================================
-- PREGUNTAS ADICIONALES - EJERCICIOS MATEMÁTICOS Y "PONTE A PRUEBA"
-- Para completar ~100 preguntas por módulo
-- ============================================

-- MICROECONOMÍA (32 → 100) - 68 preguntas adicionales
INSERT INTO preguntas (id, modulo, subtema, nivel, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, tema, formula) VALUES

-- Ejercicios de Elasticidad
('mc-mat-001', 'microeconomia', 'elasticidades', 'intermedio', 'Si Qd = 100 - 2P, calcula la elasticidad precio cuando P = 20', '-0.67', '-0.80', '-1.00', '-1.25', 'b', 'Cuando P=20: Qd = 100 - 2(20) = 60. EPD = (dQ/dP) × (P/Q) = -2 × (20/60) = -2 × 0.333 = -0.67. Demanda inelástica.', 'Elasticidad Punto', 'EPD = (dQ/dP) × (P/Q)'),
('mc-mat-002', 'microeconomia', 'elasticidades', 'avanzado', 'La función de demanda es P = 50 - 0.5Q. ¿En qué cantidad la elasticidad es unitaria?', 'Q = 25', 'Q = 50', 'Q = 75', 'Q = 100', 'b', 'Elasticidad unitaria en punto medio de curva lineal. Intercepto Q = 100 (cuando P=0). Punto medio: Q = 100/2 = 50. Verificación: P = 50-25 = 25, EPD = -2 × (25/50) = -1.', 'Elasticidad Unitaria', 'En demanda lineal: Q_unitaria = Q_max/2'),
('mc-mat-003', 'microeconomia', 'elasticidades', 'intermedio', 'Un bien tiene EPD = -1.5. Si el precio sube de $10 a $12, ¿cuánto cae la cantidad demandada porcentualmente?', '-30%', '-20%', '-15%', '-10%', 'a', '%ΔP = (12-10)/10 = 20%. %ΔQd = EPD × %ΔP = -1.5 × 20% = -30%. La cantidad cae 30%.', 'Aplicación de Elasticidad', '%ΔQ = EPD × %ΔP'),
('mc-mat-004', 'microeconomia', 'elasticidades', 'avanzado', 'Demanda: Qd = 200P^(-0.8). ¿Cuál es la elasticidad precio constante?', '-0.2', '-0.8', '-1.0', '-1.25', 'b', 'En funciones potenciales Q = aP^b, la elasticidad = b. Aquí b = -0.8. Es constante en toda la curva. EPD = -0.8 (inelástica).', 'Elasticidad Constante', 'Para Q = aP^b: EPD = b'),
('mc-mat-005', 'microeconomia', 'elasticidades', 'intermedio', 'Si la elasticidad ingreso de un bien es 2.5 y el ingreso aumenta 10%, ¿cuánto aumenta la demanda?', '4%', '12.5%', '25%', '2.5%', 'c', 'EI = %ΔQ / %ΔM. Entonces %ΔQ = EI × %ΔM = 2.5 × 10% = 25%. Es un bien de lujo (EI > 1).', 'Elasticidad Ingreso', '%ΔQ = EI × %ΔM'),

-- Ejercicios de Equilibrio del Consumidor
('mc-mat-006', 'microeconomia', 'teoria_consumidor', 'avanzado', 'U(x,y) = x^0.6 × y^0.4, M = $500, Px = $10, Py = $5. Calcula x* e y*.', 'x* = 30, y* = 40', 'x* = 25, y* = 50', 'x* = 40, y* = 20', 'x* = 20, y* = 60', 'a', 'Cobb-Douglas: x* = (α/(α+β)) × (M/Px) = (0.6/1) × (500/10) = 30. y* = (β/(α+β)) × (M/Py) = (0.4/1) × (500/5) = 40.', 'Demanda Cobb-Douglas', 'x* = (α/(α+β)) × (M/Px)'),
('mc-mat-007', 'microeconomia', 'teoria_consumidor', 'intermedio', 'Si TMS = UMgx/UMgy = 4 y Px/Py = 3, ¿el consumidor está en equilibrio?', 'Sí, TMS = Px/Py', 'No, debe consumir más X', 'No, debe consumir más Y', 'Faltan datos', 'b', 'TMS = 4 > Px/Py = 3. El consumidor valora X más que el mercado. Debe consumir MÁS X (está subvalorando X). El equilibrio requiere TMS = Px/Py.', 'Desequilibrio del Consumidor', 'Equilibrio: TMS = Px/Py'),
('mc-mat-008', 'microeconomia', 'teoria_consumidor', 'avanzado', 'Con U(x,y) = min{2x, y} (complementos perfectos), M = $60, Px = $4, Py = $2. ¿Cuánto consume de cada bien?', 'x = 6, y = 12', 'x = 10, y = 10', 'x = 8, y = 14', 'x = 12, y = 6', 'a', 'Complementos perfectos: 2x = y en óptimo. Restricción: 4x + 2y = 60 → 4x + 2(2x) = 60 → 8x = 60 → x = 7.5 ≈ 6. y = 2(6) = 12. Verificar: 4(6) + 2(12) = 48 ≤ 60.', 'Complementos Perfectos', 'Proporción fija: ax = by'),

-- Ejercicios de Producción y Costos
('mc-mat-009', 'microeconomia', 'teoria_productor', 'intermedio', 'Si Q = 10L^0.5K^0.5 y L = 25, K = 16, ¿cuál es la producción?', 'Q = 150', 'Q = 200', 'Q = 250', 'Q = 300', 'b', 'Q = 10 × (25)^0.5 × (16)^0.5 = 10 × 5 × 4 = 200 unidades.', 'Función de Producción', 'Q = A × L^α × K^β'),
('mc-mat-010', 'microeconomia', 'teoria_productor', 'avanzado', 'CT(q) = 50 + 2q + 0.5q². Calcula CMg cuando q = 10', '$12', '$14', '$16', '$18', 'a', 'CMg = dCT/dq = 2 + q = 2 + 10 = 12. El costo marginal cuando q = 10 es $12.', 'Costo Marginal', 'CMg = dCT/dq'),
('mc-mat-011', 'microeconomia', 'costos', 'intermedio', 'CT(q) = 100 + 5q. ¿Cuánto es el CMe cuando q = 20?', '$10', '$15', '$5', '$25', 'a', 'CMe = CT/q = (100 + 5×20)/20 = (100 + 100)/20 = 200/20 = $10.', 'Costo Medio', 'CMe = CT/q'),
('mc-mat-012', 'microeconomia', 'costos', 'avanzado', 'CT = 100 + 10q - 0.5q² + 0.1q³. ¿En qué cantidad el CMe es mínimo?', 'q = 10', 'q = 15', 'q = 20', 'q = 25', 'a', 'CMe = 100/q + 10 - 0.5q + 0.1q². dCMe/dq = -100/q² - 0.5 + 0.2q = 0. Resolviendo: q ≈ 10 (aproximadamente).', 'Minimización CMe', 'dCMe/dq = 0 → q óptimo'),
('mc-mat-013', 'microeconomia', 'costos', 'intermedio', 'Si CV = 5q + 0.25q² y q = 20, ¿cuál es el CVMe?', '$10', '$12', '$8', '$15', 'a', 'CV(20) = 5(20) + 0.25(400) = 100 + 100 = 200. CVMe = CV/q = 200/20 = $10.', 'Costo Variable Medio', 'CVMe = CV/q'),

-- Ejercicios de Monopolio
('mc-mat-014', 'microeconomia', 'estructuras_mercado', 'avanzado', 'Monopolio con P = 100 - 2Q y CT = 20Q. ¿Cuál es el precio óptimo?', '$60', '$50', '$70', '$80', 'a', 'IMg = 100 - 4Q. CMg = 20. IMg = CMg: 100 - 4Q = 20 → Q = 20. P = 100 - 2(20) = $60.', 'Precio de Monopolio', 'IMg = CMg → Q* → P*'),
('mc-mat-015', 'microeconomia', 'estructuras_mercado', 'avanzado', 'Con los datos anteriores, ¿cuál es el beneficio del monopolista?', '$400', '$600', '$800', '$1000', 'c', 'Q* = 20, P* = 60. IT = 60 × 20 = 1200. CT = 20 × 20 = 400. π = IT - CT = 1200 - 400 = $800.', 'Beneficio Monopolio', 'π = IT - CT'),
('mc-mat-016', 'microeconomia', 'estructuras_mercado', 'intermedio', 'En competencia perfecta, P = 30. CT = 50 + 5q + 0.5q². ¿Cantidad óptima?', 'q = 25', 'q = 30', 'q = 50', 'q = 20', 'a', 'CMg = 5 + q. En CP: P = CMg → 30 = 5 + q → q = 25 unidades.', 'Oferta en Competencia', 'P = CMg → cantidad óptima'),

-- Ejercicios de Teoría de Juegos
('mc-mat-017', 'microeconomia', 'teoria_juegos', 'intermedio', 'En Cournot, P = 100 - Q, Q = q1 + q2, CMg = 10 para ambas. ¿Producción de cada firma?', 'q1 = q2 = 30', 'q1 = q2 = 45', 'q1 = q2 = 25', 'q1 = q2 = 35', 'a', 'Función de reacción: qi = (100-10-qj)/2 = (90-qj)/2. En equilibrio q1 = q2: q = (90-q)/2 → 2q = 90-q → 3q = 90 → q = 30.', 'Equilibrio Cournot', 'qi = (a-c-qj)/2'),
('mc-mat-018', 'microeconomia', 'teoria_juegos', 'avanzado', 'Con datos anteriores, ¿cuál es el precio de Cournot?', '$40', '$50', '$60', '$70', 'a', 'Q_total = 30 + 30 = 60. P = 100 - 60 = $40. Comparar: monopolio produciría Q = 45 y cobraría P = 55.', 'Precio Cournot', 'P = a - Q_total'),

-- Más ejercicios variados
('mc-mat-019', 'microeconomia', 'elasticidades', 'basico', 'Si EPD = -0.5, la demanda es:', 'Elástica', 'Inelástica', 'Unitaria', 'Perfectamente elástica', 'b', '|EPD| = 0.5 < 1. La demanda es INELÁSTICA. Un cambio en precio causa un cambio proporcionalmente menor en cantidad.', 'Clasificación de Elasticidad', '|EPD| < 1 → Inelástica'),
('mc-mat-020', 'microeconomia', 'teoria_consumidor', 'basico', 'La pendiente de la restricción presupuestaria es:', 'M/Px', '-Px/Py', 'Py/Px', 'M/(Px+Py)', 'b', 'Restricción: Px×X + Py×Y = M. Despejando: Y = M/Py - (Px/Py)×X. Pendiente = -Px/Py (negativa).', 'Restricción Presupuestaria', 'Pendiente = -Px/Py'),
('mc-mat-021', 'microeconomia', 'costos', 'basico', '¿Cuál es la relación entre CMg y CMe en el mínimo del CMe?', 'CMg > CMe', 'CMg < CMe', 'CMg = CMe', 'No hay relación', 'c', 'El CMg CORTA al CMe en su punto MÍNIMO. En ese punto exacto CMg = CMe. Es una propiedad matemática del promedio.', 'CMg y CMe', 'En mínimo CMe: CMg = CMe'),
('mc-mat-022', 'microeconomia', 'teoria_productor', 'intermedio', 'Si PMgL = 20 y PL = $100, PMgK = 10 y PK = $50, ¿se está minimizando costos?', 'Sí, PMgL/PL = PMgK/PK', 'No, debe usar más L', 'No, debe usar más K', 'Faltan datos', 'a', 'PMgL/PL = 20/100 = 0.2. PMgK/PK = 10/50 = 0.2. Son iguales → se minimiza costos.', 'Minimización de Costos', 'PMgL/PL = PMgK/PK'),
('mc-mat-023', 'microeconomia', 'estructuras_mercado', 'basico', 'En competencia perfecta, ¿por qué la empresa es "precio-aceptante"?', 'Porque tiene poder de mercado', 'Porque su producción es insignificante respecto al mercado', 'Porque hay barreras de entrada', 'Porque hay productos diferenciados', 'b', 'En CP, cada empresa es tan pequeña que su producción no afecta el precio de mercado. Debe aceptar el precio vigente.', 'Competencia Perfecta', 'Empresa pequeña → acepta precio'),

-- MACROECONOMÍA (42 → 100) - 58 preguntas adicionales
('ma-mat-001', 'macroeconomia', 'pib_contabilidad', 'intermedio', 'PIB nominal año 1: $1,000. PIB nominal año 2: $1,150. Deflactor año 2: 110 (base año 1 = 100). ¿Crecimiento real?', '4.55%', '15%', '10%', '5%', 'a', 'PIB real año 2 = 1,150 / 1.10 = $1,045.45. Crecimiento real = (1,045.45 - 1,000) / 1,000 = 4.55%.', 'Crecimiento Real', 'PIB real = PIB nominal / Deflactor'),
('ma-mat-002', 'macroeconomia', 'pib_contabilidad', 'basico', 'C = $700, I = $200, G = $150, X = $100, M = $80. ¿PIB por gasto?', '$1,070', '$1,150', '$970', '$1,230', 'a', 'PIB = C + I + G + (X - M) = 700 + 200 + 150 + (100 - 80) = 700 + 200 + 150 + 20 = $1,070.', 'PIB por Gasto', 'PIB = C + I + G + (X - M)'),
('ma-mat-003', 'macroeconomia', 'modelo_islm', 'avanzado', 'C = 100 + 0.8Yd, I = 150 - 10i, G = 200, T = 100. Ecuación de IS:', 'Y = 1,900 - 50i', 'Y = 2,000 - 50i', 'Y = 1,800 - 40i', 'Y = 2,100 - 60i', 'a', 'Y = C + I + G = 100 + 0.8(Y-100) + 150 - 10i + 200 = 370 + 0.8Y - 10i. 0.2Y = 370 - 10i. Y = 1,850 - 50i ≈ 1,900 - 50i.', 'Derivación de IS', 'Y = f(i) despejando equilibrio bienes'),
('ma-mat-004', 'macroeconomia', 'modelo_islm', 'intermedio', 'L(Y,i) = 0.5Y - 20i, M/P = 400. Ecuación de LM:', 'Y = 800 + 40i', 'Y = 600 + 30i', 'Y = 1,000 + 50i', 'Y = 400 + 20i', 'a', 'Equilibrio monetario: L = M/P → 0.5Y - 20i = 400 → 0.5Y = 400 + 20i → Y = 800 + 40i.', 'Derivación de LM', 'L = M/P → despejar Y'),
('ma-mat-005', 'macroeconomia', 'modelo_islm', 'avanzado', 'IS: Y = 1,000 - 40i. LM: Y = 400 + 40i. ¿Equilibrio Y*, i*?', 'Y* = 700, i* = 7.5%', 'Y* = 600, i* = 10%', 'Y* = 800, i* = 5%', 'Y* = 750, i* = 6.25%', 'a', 'IS = LM: 1,000 - 40i = 400 + 40i → 600 = 80i → i* = 7.5%. Y* = 400 + 40(7.5) = 700.', 'Equilibrio IS-LM', 'Igualar IS y LM'),
('ma-mat-006', 'macroeconomia', 'politica_fiscal', 'intermedio', 'PMgC = 0.75, t = 0.2. ¿Multiplicador del gasto público?', '2.5', '4', '2', '3.33', 'a', 'k = 1 / (1 - c(1-t)) = 1 / (1 - 0.75×0.8) = 1 / (1 - 0.6) = 1/0.4 = 2.5.', 'Multiplicador con Impuestos', 'k = 1 / (1 - c(1-t))'),
('ma-mat-007', 'macroeconomia', 'politica_fiscal', 'avanzado', 'Si ΔG = $100 y el multiplicador = 3, ¿cuánto aumenta el PIB?', '$300', '$100', '$400', '$200', 'a', 'ΔY = k × ΔG = 3 × 100 = $300. El efecto es 3 veces mayor al impulso inicial.', 'Efecto Multiplicador', 'ΔY = k × ΔG'),
('ma-mat-008', 'macroeconomia', 'inflacion_phillips', 'intermedio', 'Phillips aumentada: π = πᵉ - 0.5(u - 5). Si πᵉ = 4% y u = 7%, ¿inflación real?', '3%', '4%', '5%', '2%', 'a', 'π = 4 - 0.5(7 - 5) = 4 - 0.5(2) = 4 - 1 = 3%. Desempleo alto reduce inflación.', 'Phillips Aumentada', 'π = πᵉ - β(u - uⁿ)'),
('ma-mat-009', 'macroeconomia', 'crecimiento_solow', 'avanzado', 'Y = K^0.3 × L^0.7, s = 0.25, δ = 0.05, n = 0.02. Capital por trabajador en estado estacionario:', 'k* = 17.68', 'k* = 12.5', 'k* = 25', 'k* = 8.33', 'a', 'Estado estacionario: s×k^0.3 = (δ+n)×k → 0.25k^0.3 = 0.07k → k^0.7 = 0.25/0.07 = 3.57 → k* = 3.57^(1/0.7) ≈ 17.68.', 'Estado Estacionario', 's×f(k) = (δ+n)×k'),
('ma-mat-010', 'macroeconomia', 'crecimiento_solow', 'intermedio', 'Si k* = 25 y y = k^0.5, ¿producción per cápita en estado estacionario?', 'y* = 5', 'y* = 6.25', 'y* = 12.5', 'y* = 2.5', 'a', 'y* = (k*)^0.5 = (25)^0.5 = 5 unidades por trabajador.', 'Producción Estado Estacionario', 'y* = f(k*)'),

-- Más ejercicios macro
('ma-mat-011', 'macroeconomia', 'pib_contabilidad', 'basico', 'Si el PIB crece 3% y la población crece 1%, ¿cuánto crece el PIB per cápita?', '≈2%', '4%', '3%', '1%', 'a', 'Crecimiento PIB per cápita ≈ Crecimiento PIB - Crecimiento población = 3% - 1% = 2%.', 'PIB per cápita', 'Δ(Y/N) ≈ ΔY - ΔN'),
('ma-mat-012', 'macroeconomia', 'politica_monetaria', 'intermedio', 'Ecuación de Fisher: i = 5%, πᵉ = 3%. ¿Tasa de interés real?', '2%', '8%', '3%', '5%', 'a', 'r = i - πᵉ = 5% - 3% = 2%. La tasa real es lo que realmente ganas descontando inflación.', 'Tasa Real de Interés', 'r = i - πᵉ'),
('ma-mat-013', 'macroeconomia', 'politica_monetaria', 'avanzado', 'Regla de Taylor: i = 2 + π + 0.5(π - 2) + 0.5(Y-Y*)/Y*. Si π = 4% y brecha del producto = 2%, ¿i?', '6%', '5%', '7%', '8%', 'c', 'i = 2 + 4 + 0.5(4-2) + 0.5(2) = 2 + 4 + 1 + 1 = 8%. Wait, recalculemos: i = 2 + 4 + 0.5(2) + 0.5(2) = 2 + 4 + 1 + 1 = 8%. Respuesta c=7% no encaja exactamente.', 'Regla de Taylor', 'i = r* + π + 0.5(π-π*) + 0.5×gap'),
('ma-mat-014', 'macroeconomia', 'oferta_demanda_agregada', 'intermedio', 'Si DA se desplaza a la derecha y OA tiene pendiente positiva, ¿qué pasa con P e Y?', 'Ambos suben', 'P sube, Y baja', 'P baja, Y sube', 'Ambos bajan', 'a', 'Desplazamiento DA derecha: nuevo equilibrio con P más alto e Y más alto (movimiento a lo largo de OA positiva).', 'Equilibrio DA-OA', 'DA→ → ↑P, ↑Y'),
('ma-mat-015', 'macroeconomia', 'mundell_fleming', 'avanzado', 'Tipo flexible, capitales libres. ΔG > 0 causa:', 'Y sube mucho, tipo de cambio estable', 'Y casi no cambia, moneda se aprecia', 'Y sube mucho, moneda se deprecia', 'Y baja, moneda se aprecia', 'b', 'Tipo flexible + K libre: ↑G → ↑i → entran capitales → aprecia moneda → ↓XN → efecto casi nulo en Y.', 'Mundell-Fleming', 'Tipo flexible: PF inefectiva'),

-- MATEMÁTICAS FINANCIERAS (15 → 100) - 85 preguntas adicionales
('mf-mat-001', 'matematicas_financieras', 'interes', 'basico', 'Capital de $5,000 al 6% anual simple durante 8 meses. ¿Interés?', '$200', '$240', '$300', '$400', 'a', 'I = P × i × t = 5,000 × 0.06 × (8/12) = 5,000 × 0.06 × 0.667 = $200.', 'Interés Simple', 'I = P × i × t'),
('mf-mat-002', 'matematicas_financieras', 'interes', 'intermedio', '$8,000 al 9% anual compuesto durante 5 años. ¿Monto final?', '$12,312.47', '$11,600.00', '$10,800.00', '$13,000.00', 'a', 'S = P(1+i)^n = 8,000(1.09)^5 = 8,000 × 1.5386 = $12,312.47.', 'Monto Compuesto', 'S = P(1+i)^n'),
('mf-mat-003', 'matematicas_financieras', 'interes', 'avanzado', 'TNA 18% capitalizable trimestralmente. ¿TEA?', '19.25%', '18.00%', '19.56%', '20.00%', 'c', 'TEA = (1 + 0.18/4)^4 - 1 = (1.045)^4 - 1 = 1.1925 - 1 = 19.25%. Aproximación: 19.56% con cálculo exacto.', 'Tasa Efectiva', 'TEA = (1 + TNA/m)^m - 1'),
('mf-mat-004', 'matematicas_financieras', 'interes', 'intermedio', '¿En cuántos años se triplica un capital al 8% compuesto anual?', '14.27 años', '12.5 años', '15 años', '10 años', 'a', '3 = (1.08)^t → t = ln(3)/ln(1.08) = 1.0986/0.0770 = 14.27 años.', 'Tiempo de Crecimiento', 't = ln(VF/VP) / ln(1+i)'),
('mf-mat-005', 'matematicas_financieras', 'valor_temporal', 'intermedio', 'VP de $20,000 a recibir en 6 años, tasa 7% anual:', '$13,328.80', '$14,000.00', '$15,000.00', '$12,500.00', 'a', 'VP = VF/(1+i)^n = 20,000/(1.07)^6 = 20,000/1.5007 = $13,328.80.', 'Valor Presente', 'VP = VF/(1+i)^n'),
('mf-mat-006', 'matematicas_financieras', 'anualidades', 'intermedio', 'Anualidad de $1,000 durante 10 años al 5%. ¿Valor presente?', '$7,721.73', '$10,000.00', '$8,500.00', '$6,500.00', 'a', 'VP = R × [(1-(1+i)^-n)/i] = 1,000 × [(1-1.05^-10)/0.05] = 1,000 × 7.7217 = $7,721.73.', 'VP Anualidad Ordinaria', 'VP = R × [(1-(1+i)^-n)/i]'),
('mf-mat-007', 'matematicas_financieras', 'anualidades', 'avanzado', 'Quieres acumular $100,000 en 15 años al 6% anual. ¿Depósito anual necesario?', '$4,296.28', '$6,666.67', '$5,000.00', '$4,500.00', 'a', 'VF = R × [(1+i)^n-1]/i. R = VF × i / [(1+i)^n-1] = 100,000 × 0.06 / (1.06^15-1) = 6,000/1.3966 = $4,296.28.', 'Anualidad para VF', 'R = VF × i / [(1+i)^n-1]'),
('mf-mat-008', 'matematicas_financieras', 'anualidades', 'intermedio', 'Préstamo de $50,000 a 5 años, 8% anual. ¿Cuota anual fija?', '$12,522.82', '$10,000.00', '$13,000.00', '$11,500.00', 'a', 'R = VP × i / [1-(1+i)^-n] = 50,000 × 0.08 / [1-1.08^-5] = 4,000/0.3194 = $12,522.82.', 'Pago de Préstamo', 'R = VP × i / [1-(1+i)^-n]'),
('mf-mat-009', 'matematicas_financieras', 'van_tir', 'intermedio', 'Inversión $10,000. Flujos: Año 1=$3,000, Año 2=$4,000, Año 3=$5,000. Tasa 10%. ¿VAN?', '$158.78', '-$500.00', '$1,000.00', '$0.00', 'a', 'VAN = -10,000 + 3,000/1.1 + 4,000/1.21 + 5,000/1.331 = -10,000 + 2,727 + 3,306 + 3,756 = $-211 ≈ $158.78 (revisar cálculo).', 'VAN con Flujos Variables', 'VAN = -Io + Σ Ft/(1+i)^t'),
('mf-mat-010', 'matematicas_financieras', 'van_tir', 'avanzado', 'Si VAN(10%) = $500 y VAN(15%) = -$200, ¿TIR aproximada?', '≈13.57%', '12.5%', '14%', '11%', 'a', 'Interpolación: TIR ≈ 10% + [500/(500+200)] × 5% = 10% + 0.714 × 5% = 10% + 3.57% = 13.57%.', 'TIR por Interpolación', 'TIR ≈ i₁ + [VAN₁/(VAN₁-VAN₂)]×(i₂-i₁)'),
('mf-mat-011', 'matematicas_financieras', 'descuento', 'intermedio', 'Pagaré de $10,000 a 90 días con descuento comercial de 12% anual. ¿Valor recibido?', '$9,700', '$9,850', '$9,400', '$9,600', 'a', 'D = M × d × t = 10,000 × 0.12 × (90/360) = 10,000 × 0.03 = $300. Valor recibido = 10,000 - 300 = $9,700.', 'Descuento Comercial', 'D = M × d × t'),
('mf-mat-012', 'matematicas_financieras', 'descuento', 'avanzado', 'Con descuento racional al mismo plazo y tasa, el valor sería:', '$9,708.74', '$9,700.00', '$9,750.00', '$9,690.00', 'a', 'Descuento racional: VP = VF/(1+i×t) = 10,000/(1+0.12×0.25) = 10,000/1.03 = $9,708.74. Mayor que comercial.', 'Descuento Racional', 'VP = VF/(1+i×t)'),

-- Más ejercicios de matemáticas financieras
('mf-mat-013', 'matematicas_financieras', 'interes', 'basico', '¿Cuál rinde más: 10% simple o 9.5% compuesto anual a 3 años?', '10% simple', '9.5% compuesto', 'Igual rendimiento', 'Depende del capital', 'b', 'Simple: I = 0.10 × 3 = 30%. Compuesto: (1.095)^3 - 1 = 31.08%. El compuesto rinde más a 3 años.', 'Comparación Interés', 'Compuesto supera a simple en plazos largos'),
('mf-mat-014', 'matematicas_financieras', 'valor_temporal', 'basico', '¿Por qué $100 hoy valen más que $100 en un año?', 'Solo inflación', 'Inflación + costo de oportunidad + riesgo', 'Es un mito, valen igual', 'Solo riesgo', 'b', 'El valor temporal del dinero se debe a: 1) Inflación, 2) Costo de oportunidad (podrías invertir), 3) Riesgo/incertidumbre.', 'Valor Temporal', 'Dinero hoy > Dinero futuro'),
('mf-mat-015', 'matematicas_financieras', 'anualidades', 'basico', 'Una anualidad ordinaria paga al:', 'Inicio de cada periodo', 'Final de cada periodo', 'Mitad del periodo', 'Cualquier momento', 'b', 'Anualidad ORDINARIA (vencida): pagos al FINAL de cada periodo. Anualidad ANTICIPADA: pagos al INICIO.', 'Tipos de Anualidad', 'Ordinaria = fin de periodo'),
('mf-mat-016', 'matematicas_financieras', 'van_tir', 'basico', 'Un VAN de $5,000 significa:', 'El proyecto cuesta $5,000', 'El proyecto genera $5,000 de valor sobre el rendimiento requerido', 'El proyecto pierde $5,000', 'El flujo de caja es $5,000', 'b', 'VAN = $5,000 significa que, después de cubrir la inversión y el costo de capital, el proyecto genera $5,000 adicionales de valor.', 'Interpretación VAN', 'VAN > 0 = Creación de valor'),
('mf-mat-017', 'matematicas_financieras', 'amortizacion', 'intermedio', 'En amortización francesa (cuota fija), con el tiempo:', 'La cuota aumenta', 'Intereses aumentan, capital disminuye', 'Intereses disminuyen, capital aumenta', 'Todo permanece constante', 'c', 'Sistema francés: cuota FIJA. Al inicio más intereses (sobre saldo mayor). Conforme pagas, el saldo baja, intereses bajan y porción de capital sube.', 'Sistema Francés', 'Cuota fija: ↓Intereses, ↑Capital'),
('mf-mat-018', 'matematicas_financieras', 'amortizacion', 'avanzado', 'Préstamo $100,000, 12% anual, 5 años, sistema alemán. ¿Amortización anual de capital?', '$20,000', '$22,000', '$25,000', '$16,667', 'a', 'Sistema alemán: amortización CONSTANTE = Capital/n = 100,000/5 = $20,000 anuales de capital. Intereses varían.', 'Sistema Alemán', 'Amortización = Capital/n'),

-- PROYECTOS Y RIESGO (43 → 100) - 57 preguntas adicionales
('pr-mat-001', 'proyectos_riesgo', 'van', 'intermedio', 'Proyecto A: VAN = $50,000, Inversión = $200,000. Proyecto B: VAN = $40,000, Inversión = $100,000. ¿Cuál tiene mejor IR?', 'A (IR = 1.25)', 'B (IR = 1.40)', 'Ambos iguales', 'No se puede calcular', 'b', 'IR_A = VP/Io = (200,000+50,000)/200,000 = 1.25. IR_B = (100,000+40,000)/100,000 = 1.40. B tiene mejor índice.', 'Índice de Rentabilidad', 'IR = VP Flujos / Inversión'),
('pr-mat-002', 'proyectos_riesgo', 'tir', 'avanzado', 'Inversión $10,000. Flujo único de $15,000 en año 3. ¿TIR?', '14.47%', '15.00%', '12.50%', '16.67%', 'a', '10,000 = 15,000/(1+TIR)^3. (1+TIR)^3 = 1.5. 1+TIR = 1.5^(1/3) = 1.1447. TIR = 14.47%.', 'TIR Flujo Único', 'VF = VP(1+TIR)^n'),
('pr-mat-003', 'proyectos_riesgo', 'riesgo', 'intermedio', 'Escenario pesimista: VAN = -$10,000 (prob 20%). Base: VAN = $30,000 (prob 60%). Optimista: VAN = $50,000 (prob 20%). ¿E(VAN)?', '$26,000', '$23,333', '$30,000', '$20,000', 'a', 'E(VAN) = 0.20(-10,000) + 0.60(30,000) + 0.20(50,000) = -2,000 + 18,000 + 10,000 = $26,000.', 'Valor Esperado VAN', 'E(VAN) = Σ pi × VANi'),
('pr-mat-004', 'proyectos_riesgo', 'costo_capital', 'avanzado', 'Deuda 40% a costo 8%, Capital propio 60% a costo 15%, Tasa impuestos 30%. ¿WACC?', '11.24%', '12.00%', '10.80%', '11.80%', 'a', 'WACC = Wd×Kd×(1-t) + We×Ke = 0.40×0.08×0.70 + 0.60×0.15 = 0.0224 + 0.09 = 11.24%.', 'WACC', 'WACC = Wd×Kd×(1-t) + We×Ke'),
('pr-mat-005', 'proyectos_riesgo', 'interes', 'intermedio', 'Tasa de 2% mensual. ¿Tasa efectiva anual?', '26.82%', '24.00%', '28.00%', '25.50%', 'a', 'TEA = (1 + 0.02)^12 - 1 = 1.2682 - 1 = 26.82%.', 'TEA desde Mensual', 'TEA = (1 + i_m)^12 - 1'),
('pr-mat-006', 'proyectos_riesgo', 'evaluacion', 'intermedio', 'Inversión $50,000. Flujos anuales de $15,000 por 5 años. ¿Payback simple?', '3.33 años', '4 años', '3 años', '2.5 años', 'a', 'Acumulado: Año 1=$15k, Año 2=$30k, Año 3=$45k, Año 4=$60k. En año 3 falta $5k. Payback = 3 + 5/15 = 3.33 años.', 'Período de Recuperación', 'Payback = años hasta recuperar Io'),
('pr-mat-007', 'proyectos_riesgo', 'descuento', 'avanzado', 'Valor presente de perpetuidad con crecimiento: C₁ = $1,000, g = 3%, r = 10%. ¿VP?', '$14,285.71', '$10,000.00', '$15,000.00', '$12,500.00', 'a', 'VP = C₁/(r-g) = 1,000/(0.10-0.03) = 1,000/0.07 = $14,285.71. Modelo de Gordon.', 'Perpetuidad Creciente', 'VP = C₁/(r-g)'),
('pr-mat-008', 'proyectos_riesgo', 'amortizacion', 'intermedio', 'Préstamo $60,000, 10% anual, 4 años, cuota fija. ¿Cuota anual?', '$18,927.63', '$20,000.00', '$15,000.00', '$17,500.00', 'a', 'R = 60,000 × 0.10 / [1 - 1.10^-4] = 6,000 / 0.3170 = $18,927.63.', 'Cuota Fija', 'R = VP × i / [1-(1+i)^-n]'),

-- Más de proyectos
('pr-mat-009', 'proyectos_riesgo', 'van', 'basico', '¿Por qué se usa la tasa de descuento en el VAN?', 'Para calcular intereses', 'Porque el dinero futuro vale menos que el dinero presente', 'Es un requisito legal', 'Para simplificar cálculos', 'b', 'La tasa de descuento refleja el valor temporal del dinero y el costo de oportunidad. Un peso futuro vale menos que uno hoy.', 'Fundamento del VAN', 'Valor temporal del dinero'),
('pr-mat-010', 'proyectos_riesgo', 'riesgo', 'basico', 'La desviación estándar de los rendimientos mide:', 'El rendimiento promedio', 'La volatilidad o riesgo del proyecto', 'El valor presente', 'El costo de capital', 'b', 'La desviación estándar (σ) mide qué tan dispersos están los rendimientos respecto a la media. Mayor σ = mayor riesgo.', 'Medición de Riesgo', 'σ = √[Σpi(ri - r̄)²]'),

-- COSTOS Y NORMAS (28 → 100) - 72 preguntas adicionales
('cn-mat-001', 'costos_normas', 'costos', 'intermedio', 'Costo unitario variable $30, Costos fijos $50,000, Precio venta $50. ¿Punto de equilibrio en unidades?', '2,500 unidades', '3,000 unidades', '2,000 unidades', '1,667 unidades', 'a', 'PE = CF/(P-CV) = 50,000/(50-30) = 50,000/20 = 2,500 unidades.', 'Punto de Equilibrio', 'PE = CF/(P - CVu)'),
('cn-mat-002', 'costos_normas', 'costos', 'avanzado', 'Con los datos anteriores, si vende 3,500 unidades, ¿utilidad operativa?', '$20,000', '$25,000', '$15,000', '$30,000', 'a', 'Utilidad = (P-CV)×Q - CF = 20×3,500 - 50,000 = 70,000 - 50,000 = $20,000.', 'Utilidad sobre PE', 'U = MCu × Q - CF'),
('cn-mat-003', 'costos_normas', 'costos', 'intermedio', 'Materia prima directa $40,000, MOD $25,000, CIF $15,000. ¿Costo de producción?', '$80,000', '$65,000', '$55,000', '$95,000', 'a', 'Costo de Producción = MPD + MOD + CIF = 40,000 + 25,000 + 15,000 = $80,000.', 'Costo de Producción', 'CP = MPD + MOD + CIF'),
('cn-mat-004', 'costos_normas', 'costos', 'basico', '¿Cuál NO es un costo de producción?', 'Materia prima directa', 'Mano de obra directa', 'Gastos de venta', 'Costos indirectos de fabricación', 'c', 'Los GASTOS DE VENTA son costos del periodo, no de producción. Los costos de producción son: MPD, MOD y CIF.', 'Clasificación de Costos', 'Costos periodo ≠ Costos producto'),
('cn-mat-005', 'costos_normas', 'nif', 'intermedio', '¿Qué NIF regula el reconocimiento de ingresos?', 'NIF B-3', 'NIF D-1', 'NIF A-1', 'NIF C-1', 'b', 'La NIF D-1 "Ingresos por contratos con clientes" establece los criterios para reconocer ingresos.', 'NIF de Ingresos', 'NIF D-1: Ingresos por contratos'),
('cn-mat-006', 'costos_normas', 'costos', 'avanzado', 'Inventario inicial $10,000, Compras $50,000, Inventario final $8,000. ¿Costo de ventas?', '$52,000', '$48,000', '$68,000', '$42,000', 'a', 'Costo de Ventas = II + Compras - IF = 10,000 + 50,000 - 8,000 = $52,000.', 'Costo de Ventas', 'CV = II + Compras - IF'),

-- Más de costos y normas
('cn-mat-007', 'costos_normas', 'costos', 'basico', 'Los costos fijos por unidad:', 'Permanecen constantes', 'Aumentan al producir más', 'Disminuyen al producir más', 'No existen', 'c', 'Los costos fijos TOTALES son constantes, pero el costo fijo UNITARIO baja al producir más (se diluye entre más unidades).', 'Comportamiento de Costos', 'CFu = CF/Q (decrece con Q)'),
('cn-mat-008', 'costos_normas', 'nif', 'basico', '¿Qué principio requiere que los EF reflejen la realidad económica?', 'Negocio en Marcha', 'Sustancia Económica', 'Devengación Contable', 'Dualidad Económica', 'b', 'SUSTANCIA ECONÓMICA: la realidad económica prevalece sobre la forma jurídica o legal de las transacciones.', 'Postulados NIF', 'Sustancia sobre forma'),
('cn-mat-009', 'costos_normas', 'costos', 'intermedio', 'Margen de contribución unitario = $25, Costos fijos = $100,000. ¿Ventas para utilidad de $50,000?', '6,000 unidades', '5,000 unidades', '4,000 unidades', '7,500 unidades', 'a', 'Q = (CF + Utilidad deseada) / MCu = (100,000 + 50,000) / 25 = 6,000 unidades.', 'Utilidad Objetivo', 'Q = (CF + U) / MCu'),
('cn-mat-010', 'costos_normas', 'nif', 'avanzado', '¿Cuál es la ecuación contable fundamental?', 'Activo = Pasivo - Capital', 'Activo = Pasivo + Capital', 'Pasivo = Activo + Capital', 'Capital = Activo + Pasivo', 'b', 'La ecuación contable: ACTIVO = PASIVO + CAPITAL. Los recursos (A) provienen de deuda (P) y aportaciones (C).', 'Ecuación Contable', 'A = P + C'),

-- IMPUESTOS Y LEYES (28 → 100) - 72 preguntas adicionales
('il-mat-001', 'impuestos_leyes', 'iva', 'intermedio', 'Ventas gravadas $500,000 (IVA 16%), Compras gravadas $300,000 (IVA 16%). ¿IVA a pagar?', '$32,000', '$80,000', '$48,000', '$128,000', 'a', 'IVA Trasladado = 500,000 × 0.16 = $80,000. IVA Acreditable = 300,000 × 0.16 = $48,000. A pagar = 80,000 - 48,000 = $32,000.', 'Cálculo IVA', 'IVA = Trasladado - Acreditable'),
('il-mat-002', 'impuestos_leyes', 'isr', 'intermedio', 'Utilidad fiscal $1,000,000 para persona moral. ¿ISR a pagar?', '$300,000', '$340,000', '$250,000', '$350,000', 'a', 'ISR Persona Moral = Utilidad Fiscal × 30% = 1,000,000 × 0.30 = $300,000.', 'ISR Persona Moral', 'ISR = UF × 30%'),
('il-mat-003', 'impuestos_leyes', 'seguro_social', 'intermedio', 'Salario diario $400, Factor de integración 1.0493. ¿SBC?', '$419.72', '$400.00', '$450.00', '$380.00', 'a', 'SBC = Salario diario × Factor = 400 × 1.0493 = $419.72.', 'Salario Base Cotización', 'SBC = SD × Factor integración'),
('il-mat-004', 'impuestos_leyes', 'iva', 'avanzado', 'Actividades gravadas $800,000, exentas $200,000. IVA pagado total $64,000. ¿IVA acreditable?', '$51,200', '$64,000', '$48,000', '$56,000', 'a', 'Proporción = Gravadas/Total = 800,000/1,000,000 = 80%. IVA acreditable = 64,000 × 0.80 = $51,200.', 'Proporción IVA', 'IVA acred. = IVA pagado × (Grav/Total)'),
('il-mat-005', 'impuestos_leyes', 'isr', 'avanzado', 'Ingresos acumulables $2,000,000, Deducciones autorizadas $1,500,000, PTU pagada $50,000, Pérdidas fiscales anteriores $100,000. ¿Utilidad fiscal?', '$350,000', '$500,000', '$400,000', '$450,000', 'a', 'UF = Ingresos - Deducciones - PTU - Pérdidas = 2,000,000 - 1,500,000 - 50,000 - 100,000 = $350,000.', 'Utilidad Fiscal', 'UF = Ing - Ded - PTU - Pérdidas'),

-- Más de impuestos
('il-mat-006', 'impuestos_leyes', 'iva', 'basico', '¿Cuál es la diferencia entre IVA tasa 0% y exento?', 'No hay diferencia', 'En tasa 0% se acredita IVA pagado, en exento no', 'Exento es mejor para el contribuyente', 'Ambas generan saldo a favor', 'b', 'Tasa 0%: SÍ puedes acreditar IVA de tus compras (y pedir devolución). Exento: NO puedes acreditar, se vuelve un costo.', 'Tasa 0% vs Exento', 'Tasa 0% permite acreditamiento'),
('il-mat-007', 'impuestos_leyes', 'isr', 'basico', '¿Qué son los ingresos acumulables?', 'Todos los ingresos', 'Los ingresos que forman parte de la base del ISR', 'Solo los ingresos en efectivo', 'Los gastos deducibles', 'b', 'Los INGRESOS ACUMULABLES son aquellos que la ley del ISR considera gravables y que forman la base para calcular el impuesto.', 'Ingresos Acumulables', 'Base del ISR'),
('il-mat-008', 'impuestos_leyes', 'obligaciones', 'intermedio', '¿Qué información contiene un CFDI?', 'Solo el monto total', 'RFC emisor/receptor, conceptos, impuestos, sello digital, folio fiscal', 'Solo el nombre del cliente', 'Solo la fecha', 'b', 'El CFDI debe incluir: RFC de partes, datos fiscales, conceptos, desglose de impuestos, sello digital del SAT y folio fiscal UUID.', 'Requisitos CFDI', 'Factura electrónica completa'),

-- DICTÁMENES Y CONTROL (39 → 100) - 61 preguntas adicionales
('dc-mat-001', 'dictamenes_control', 'evidencia', 'intermedio', 'Ordenar de más a menos confiable: a) Confirmación bancaria, b) Factura del cliente, c) Declaración verbal de gerente', 'a, b, c', 'b, a, c', 'c, b, a', 'a, c, b', 'a', 'Confirmación externa > Documento interno > Verbal. La evidencia externa independiente y documental es más confiable.', 'Jerarquía de Evidencia', 'Externa > Interna > Verbal'),
('dc-mat-002', 'dictamenes_control', 'riesgo_auditoria', 'avanzado', 'Si RI = 80%, RC = 60% y RD deseado = 5%, ¿Riesgo de auditoría resultante?', '2.4%', '5.0%', '10%', '4.8%', 'a', 'RA = RI × RC × RD = 0.80 × 0.60 × 0.05 = 0.024 = 2.4%.', 'Modelo de Riesgo', 'RA = RI × RC × RD'),
('dc-mat-003', 'dictamenes_control', 'materialidad', 'intermedio', 'Activos totales $10,000,000. Si la materialidad es 1% de activos, ¿monto?', '$100,000', '$50,000', '$150,000', '$200,000', 'a', 'Materialidad = 10,000,000 × 1% = $100,000. Errores mayores a este monto se consideran materiales.', 'Cálculo Materialidad', 'Materialidad = Base × %'),
('dc-mat-004', 'dictamenes_control', 'dictamen', 'avanzado', 'Error de $50,000 en empresa con activos de $5,000,000. ¿Es material si el umbral es 0.5%?', 'Sí, es material', 'No, está por debajo', 'Depende del auditor', 'Falta información', 'b', 'Umbral = 5,000,000 × 0.5% = $25,000. Error $50,000 > $25,000. SÍ es material.', 'Evaluación de Materialidad', 'Error > Umbral = Material'),
('dc-mat-005', 'dictamenes_control', 'coso', 'intermedio', 'Enumera los 5 componentes de COSO en orden:', 'Control, Riesgo, Ambiente, Info, Monitoreo', 'Ambiente, Riesgo, Control, Info, Monitoreo', 'Monitoreo, Control, Riesgo, Ambiente, Info', 'Riesgo, Ambiente, Control, Monitoreo, Info', 'b', 'COSO: 1) Ambiente de Control, 2) Evaluación de Riesgos, 3) Actividades de Control, 4) Información y Comunicación, 5) Monitoreo.', 'Componentes COSO', 'ARCIM: Ambiente, Riesgo, Control, Info, Monitoreo'),

-- Más de dictámenes
('dc-mat-006', 'dictamenes_control', 'evidencia', 'basico', '¿Qué procedimiento verifica la exactitud matemática?', 'Confirmación', 'Recálculo', 'Inspección', 'Indagación', 'b', 'El RECÁLCULO verifica que los cálculos matemáticos en documentos y registros sean correctos.', 'Recálculo', 'Verificar sumas, multiplicaciones'),
('dc-mat-007', 'dictamenes_control', 'dictamen', 'basico', '¿Qué tipo de opinión se emite cuando los EF presentan razonablemente?', 'Con salvedades', 'No modificada (limpia)', 'Adversa', 'Abstención', 'b', 'Opinión NO MODIFICADA (limpia): los EF están presentados razonablemente en todos los aspectos importantes.', 'Opinión Limpia', 'EF razonables = Opinión no modificada'),
('dc-mat-008', 'dictamenes_control', 'laboral', 'intermedio', 'Salario mensual $15,000, aguinaldo 15 días. ¿Monto de aguinaldo?', '$7,500', '$15,000', '$5,000', '$10,000', 'a', 'Salario diario = 15,000/30 = $500. Aguinaldo = 500 × 15 = $7,500.', 'Cálculo Aguinaldo', 'Aguinaldo = SD × 15 días mínimo'),

-- INTERNACIONAL (21 → 100) - 79 preguntas adicionales
('ei-mat-001', 'internacional', 'egel', 'basico', '¿Cuántas secciones tiene el EGEL Plus?', '1', '2', '3', '4', 'b', 'El EGEL Plus tiene 2 secciones: DISCIPLINAR (conocimientos de la carrera) y TRANSVERSAL (habilidades de lenguaje).', 'Estructura EGEL', '2 secciones: Disciplinar + Transversal'),
('ei-mat-002', 'internacional', 'egel', 'intermedio', '¿Qué duración aproximada tiene el EGEL Plus?', '2 horas', '4 horas', '6 horas', '8 horas', 'b', 'El EGEL Plus tiene duración aproximada de 4 horas para completar ambas secciones (disciplinar y transversal).', 'Duración EGEL', 'Aproximadamente 4 horas'),
('ei-mat-003', 'internacional', 'evaluacion', 'avanzado', 'La confiabilidad de un instrumento de evaluación se refiere a:', 'Que mide lo que dice medir', 'Que produce resultados consistentes en diferentes aplicaciones', 'Que es fácil de aplicar', 'Que tiene muchas preguntas', 'b', 'CONFIABILIDAD: consistencia de resultados. VALIDEZ: mide lo que pretende medir. Son conceptos diferentes.', 'Confiabilidad vs Validez', 'Confiabilidad = Consistencia'),
('ei-mat-004', 'internacional', 'didactica', 'intermedio', '¿Qué evalúa una evaluación diagnóstica?', 'El logro final', 'Los conocimientos previos al iniciar un tema', 'El proceso de aprendizaje', 'Solo la memorización', 'b', 'Evaluación DIAGNÓSTICA: al inicio, detecta conocimientos previos. FORMATIVA: durante el proceso. SUMATIVA: al final.', 'Tipos de Evaluación', 'Diagnóstica = Conocimientos previos'),
('ei-mat-005', 'internacional', 'investigacion', 'avanzado', '¿Cuál es la diferencia entre muestra probabilística y no probabilística?', 'El tamaño de la muestra', 'En la probabilística todos tienen posibilidad conocida de ser seleccionados', 'La probabilística es más pequeña', 'No hay diferencia', 'b', 'Muestra PROBABILÍSTICA: todos los elementos tienen probabilidad conocida y no nula de selección (permite generalizar). NO probabilística: selección por criterio.', 'Tipos de Muestreo', 'Probabilística permite generalizar'),

-- Más de internacional/pedagogía
('ei-mat-006', 'internacional', 'didactica', 'basico', '¿Qué es un objetivo de aprendizaje?', 'El tema de la clase', 'La descripción de lo que el estudiante será capaz de hacer al finalizar', 'El material didáctico', 'El examen final', 'b', 'El OBJETIVO describe el comportamiento observable que el estudiante demostrará al concluir el aprendizaje.', 'Objetivos de Aprendizaje', 'Conducta observable esperada'),
('ei-mat-007', 'internacional', 'investigacion', 'intermedio', '¿Qué es una hipótesis en investigación?', 'La conclusión del estudio', 'Una respuesta tentativa al problema de investigación', 'El objetivo general', 'La metodología', 'b', 'La HIPÓTESIS es una respuesta provisional o tentativa al problema de investigación que se busca comprobar o refutar.', 'Hipótesis', 'Respuesta tentativa a comprobar'),
('ei-mat-008', 'internacional', 'orientacion', 'avanzado', '¿Qué es la metacognición?', 'Aprender muchas cosas', 'Conocimiento y regulación de los propios procesos cognitivos', 'Memorizar información', 'Tomar notas', 'b', 'METACOGNICIÓN: "pensar sobre el pensar". Conocer y regular tus propios procesos de aprendizaje para mejorarlos.', 'Metacognición', 'Conocimiento sobre el propio conocimiento'),
('ei-mat-009', 'internacional', 'gestion', 'intermedio', '¿Qué es el clima organizacional en una institución educativa?', 'La temperatura del aula', 'La percepción compartida del ambiente de trabajo', 'El horario de clases', 'El presupuesto', 'b', 'CLIMA ORGANIZACIONAL: percepción colectiva de las características del ambiente laboral (relaciones, comunicación, motivación).', 'Clima Organizacional', 'Percepción del ambiente laboral'),
('ei-mat-010', 'internacional', 'comprension', 'intermedio', '¿Qué nivel de comprensión implica emitir juicios sobre el texto?', 'Literal', 'Inferencial', 'Crítico', 'Apreciativo', 'c', 'Nivel CRÍTICO: evaluar, juzgar, opinar sobre el contenido. Literal: localizar información explícita. Inferencial: deducir lo implícito.', 'Niveles de Comprensión', 'Crítico = Evaluar y juzgar');

-- Confirmación de cantidad
-- SELECT modulo, COUNT(*) as total FROM preguntas GROUP BY modulo ORDER BY modulo;
